### ISSUE TITLE
[FEATURE REQUEST] release static builds of each version

### ISSUE THREAD

**Issue by jonathanong** [P-H-C/phc-winner-argon2#100]
i'd like to use this in an AWS lambda and i'd prefer not to have to `make` every time. you could publish each static build in the github release.

**Comment by thibaultCha** [comment]
On a side note, is [20151206](https://github.com/P-H-C/phc-winner-argon2/releases/tag/20151206) currently the only published release? I see a 1.3 branch but no previous `1.x` branch nor tag.

Could we have some clarifications as to where to look for releases and if future ones will follow a different scheme than the one linked above?

**Comment by veorq** [comment]
1.3 is under review, and introduces changes in the algorithm. If approved
it will be the next release.

**Comment by thibaultCha** [comment]
Thank you for clarifying

**Comment by technion** [comment]
I'm not aware of many (any?) similar library that offer precompiled builds, or take on the associated management and maintenance. I'm not following what build process will build the rest of your application but can't build this library as an automated component. Can you clarify?

**Comment by technion** [comment]
@veorq  Any estimates on this review? It's clearly a major breaking change for users and I'd like to prepare for it as best as possible.

**Comment by thibaultCha** [comment]
Yes, same as @technion, I would like to prepare for it too.

**Comment by veorq** [comment]
I and @sneves reviewed the changes in 1.3, and I guess @khovratovich / @daniel-dinu are planning to merge (guys?)

**Comment by technion** [comment]
This issue got somewhat sidetracked.

In the interests of cleaning up issues prior to stable release, could someone comment on, or close this issue? Personally, I feel my earlier questions were reasonable and in the absence of a response, a closure would be suitable.

**Comment by khovratovich** [comment]
Unless objections from other administrators, we will close this and make a release ASAP.

**Comment by sneves** [comment]
No objection from me.

**Comment by veorq** [comment]
Go

**Comment by jedisct1** [comment]
I wouldn't release anything on April 1st.
