### ISSUE TITLE
make test failed with clang

### ISSUE THREAD

**Issue by Arthur111** [P-H-C/phc-winner-argon2#101]
> clang: error: unsupported argument 'undefined' to option 'fsanitize='

i just remove "-fsanitize=address -fsanitize=undefined" on Makefile test: and its ok.

**Comment by technion** [comment]
These flags are incredibly valuable to the quality of the overall build - I'd suggest the solution is not to "just remove" them from the mainline.

**Comment by technion** [comment]
I have pushed a workaround for this. Note, both my test environment and the Travis environment test using clang. The errors you present relate to using a much older version.
