### ISSUE TITLE
AppVeyor needs a Visual Studio project or solution file

### ISSUE THREAD

**Issue by veorq** [P-H-C/phc-winner-argon2#107]
self-explanatory

**Comment by sneves** [comment]
According to the [documentation](https://www.appveyor.com/docs/build-phase), Appveyor looks for a VS solution by default, but it can also work with an adequate `appveyor.yml` config file.

**Comment by daniel-dinu** [comment]
I think the best would be to have builds using both Visual Studio and Cygwin.
If someone wants to work on this, the project builds on AppVeyor: https://ci.appveyor.com/project/P-H-C/phc-winner-argon2

**Comment by SparkDustJoe** [comment]
I was attempting a VS build before all the major code updates started
rolling in.  At some point I also want to port Argon2 to C#.  I can take a
look at it and see if the master branch builds and look at Appveyor this
weekend perhaps.

**Comment by alipha** [comment]
@SparkDustJoe fyi, I'm mostly done with a C# binding for argon2 already. https://github.com/alipha/csharp-argon2

**Comment by daniel-dinu** [comment]
I added support for CI using AppVeyor in branch [test-ci](/P-H-C/phc-winner-argon2/tree/test-ci). Feel free to improve.
