### ISSUE TITLE
Version number in the hash string

### ISSUE THREAD

**Issue by khovratovich** [P-H-C/phc-winner-argon2#117]
The encoded hash string should contain the version number (when it is omitted it should be v.1.2). The code should be able to parse the version number and run the relevant version of the hash function to ensure backward compatibility.

**Comment by jedisct1** [comment]
Since there is now a dedicated issue for this, I would suggest using `v=<ARGON2_VERSION_NUMBER>` in order to avoid having different identifiers for the same version.

This would be `v=19` for the current version.

**Comment by daniel-dinu** [comment]
@hynek, @bwesterb, @jedisct1 does the implementation from branch [decode](/P-H-C/phc-winner-argon2/tree/decode) break something? 
Do you encounter other backward compatibility issues?

**Comment by jedisct1** [comment]
Looks good to me!

**Comment by hynek** [comment]
Looks good: https://github.com/hynek/argon2_cffi/pull/9

**Comment by hynek** [comment]
Is there a roadmap for finalization of 1.3?  I hope to be able to push out an argon2_cffi before the first argon2-enabled Django hits PyPI such that nobody has to re-hash.

**Comment by technion** [comment]
Given the new merge, is there anything pending on this ticket?

**Comment by sneves** [comment]
I think the `decode` branch merge addressed this problem. Anyone?

**Comment by hynek** [comment]
Everything looks good to me (I asked before the decode merge :)).  As far as I’m concerned, I could cut a release anytime.  But I seem to remember tho that @khovratovich mentioned you’d do something like a release now?

**Comment by khovratovich** [comment]
I am fine with release. @veorq @sneves @daniel-dinu  ???

**Comment by veorq** [comment]
Go

**Comment by daniel-dinu** [comment]
Fine for me. I suggest solving the open issues/pull requests before the release though.

**Comment by khovratovich** [comment]
Please proceed at will

On Mon, Apr 4, 2016 at 11:07 AM, daniel-dinu <notifications@github.com>
wrote:

> Fine for me. I suggest solving the open issues/pull requests before the
> release though.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/P-H-C/phc-winner-argon2/issues/117#issuecomment-205204464>
>



-- 
Best regards,
Dmitry Khovratovich

**Comment by daniel-dinu** [comment]
If no other issues, please proceed with the release.

**Comment by daniel-dinu** [comment]
The new release is out!
