### ISSUE TITLE
memset_s wrong arguments?

### ISSUE THREAD

**Issue by mkj** [P-H-C/phc-winner-argon2#118]
The call to memset_s() doesn't match the normal arguments (assume it's calling a libc function and I'm not missing some local function of the same name)

`memset_s(v, n);`

my manpage has 
`errno_t memset_s(void *s, rsize_t smax, int c, rsize_t n);`

https://github.com/P-H-C/phc-winner-argon2/blob/54617af02de0055b90e39c4204058bb9a84c2b78/src/core.c#L106

**Comment by sneves** [comment]
You're right. Good thing almost no toolchain implements `memset_s`. Fixed in 0349d5126ada27f2e4cc7a84c883ca9207e58f03

**Comment by mkj** [comment]
Thanks. Recent osx has it.
