### ISSUE TITLE
argon2_verify does not guard against NULL-pointer for encoded parameter

### ISSUE THREAD

**Issue by cjlarose** [P-H-C/phc-winner-argon2#120]
Most other inputs to public-facing functions seem to be checked against the NULL-pointer and return an error code for it.

`argon2_verify` does not do this for its `const char *encoded` parameter, resulting in the possibility of a segfault.

Would be be a good idea to add a new error code (say, `ARGON2_ENCODED_PTR_NULL = -36`) and return it from `argon2_verify` in this case?

**Comment by technion** [comment]
I started looking at this and.. is it not fair to suggest passing a NULL should just trigger ARGON2_DECODING_FAIL?  I feel it's accurate to suggest you could not decode such a thing.

I'm writing a PR on this now.

**Comment by cjlarose** [comment]
@technion Sounds pretty reasonable to use `ARGON2_DECODING_FAIL` for this case. Thanks for looking into it!

**Comment by technion** [comment]
@cjlarose Np, PR submitted.
