### ISSUE TITLE
Other hash algorithms instead blake ?

### ISSUE THREAD

**Issue by Arthur111** [P-H-C/phc-winner-argon2#123]
In Argon -V3 doc
https://password-hashing.net/submissions/specs/Argon-v3.pdf

2.2.4 Possible future extensions

Support for other hash functions / Any cryptographically strong hash function may replace Blake2b for the initial and the final phases. However, if it does not support variable output length natively, some care should be taken when implementing it.

--

I saw there is no apis (interface) to replace Blake by another algorithm (Sha3 (FIPS202) for example).
Blake headers are called in core.c, opt.c instead of api (Hash.h for example)

In that way hash algorithm can be put in api (Hash.h and Hash.c or example).

For example i don't call Argon2 in my applications.
I call PasswordHash.c (an api) where recently i replaced PBKDF2 by Argon2.

As Moses came down from Mount Sinai with the 10 Commandments written in stone, Argon2 melted Blake in its specifications. :)

**Comment by technion** [comment]
The spec may allow it but I don't see a sensible reason to actually implement it within a distributed library. Adding a moving part like this is almost certain to encourage someone to come up with a broken implementation.

**Comment by Arthur111** [comment]
Fips202 (Sha3, Keccak) is a standard, Blake is not.
Fips202 is 3 .c files and not a library. [https://github.com/gvanas/KeccakCodePackage](url)
You can validate Blake with your testcase but let Argon2 be implemented with the hash standard.
Its just a design problem.
See Fortuna for example [https://github.com/waitman/libfortuna/blob/master/src/fortuna.c](url)

**Comment by technion** [comment]
Blake2b is an IETF standard documented in RFC7693.

**Comment by Arthur111** [comment]
Blake lost the last round of SHA3.
Its not Fips202.
Argon2 does not use a Hash standard (SHA1, 2, 3).

Here is the Argon2 documentation : 

Support for other hash functions / Any cryptographically strong hash function may replace Blake2b for the initial and the final phases.

--

The point is there is no support to do it. There is no apis to do it.

There is other projects if you are interested with open hash algorithm implementation 

https://github.com/floodyberry/ed25519-donna/blob/master/ed25519-hash-custom.h
https://github.com/jedisct1/libsodium/tree/master/src/libsodium

**Comment by sneves** [comment]
Refer to the [current version](https://github.com/P-H-C/phc-winner-argon2/blob/master/argon2-specs.pdf) of Argon2, not an earlier PHC candidate document. There is no support for other hash functions at this point---it would be a compatibility/interoperability mess.

**Comment by Arthur111** [comment]
> There is no support for other hash functions at this point.

Ok.
Thank you
