### ISSUE TITLE
AutoTool'd Argon2

### ISSUE THREAD

**Issue by janetizzy** [P-H-C/phc-winner-argon2#133]
Not yet ready for a pull request, but the basics are working now, see:
https://github.com/janetizzy/phc-winner-argon2/tree/autotool
(that's the 'autotool' branch of the tree)

**Comment by janetizzy** [comment]
I actually started this little project before reading all the 'closed' issues about portability.
I did see where one poster suggested CMAKE -
Which I don't know well enough to write in, so AutoTools it is for now.

**Comment by technion** [comment]
Autotools has been raised before in #22.  I'd suggest waiting for project owner feedback before investing further time.

**Comment by janetizzy** [comment]
@technion -
Thanks for the feedback.
But I need it for my own purposes.

**Comment by veorq** [comment]
Thanks @janetizzy! However, #22 and #38 sounded like it isn't worthwhile at the moment. But if you need it, others probably do too. Could you describe why?

**Comment by janetizzy** [comment]
To gain acceptance in a production environment, it needs to present a familar face.
Love it or Hate it, AutoTools is one of those familar faces.

All of the heavy calculations are done in the system's vector processor - -
If and only if the processor is AMD/Intel.
Not all servers run AMD/Intel - 
You have IBM with their Power8 server clusters, Oracle Solaris (on Sparc) shouldn't be forgotten about.
And it is the server that has the heavy demand to verify offered passwords. 
I have set-up the configure.ac, makefile.am (the only two files in my fork) to deal with 'translating' from the AMD/Intel dialect of vector operations to those of another processor.

Linux is gaining presence in server placements, but the 'run forever, never down' OS was, and still is, freeBSD.
There are an uncountable number of those server installations still up and running.
The vector instruction headers are provided by the compiler.
And GCC isn't the primary compiler on *BSD.

And then we shouldn't forget about HP -
Although they have dropped support for everything except the "heavy iron" (ia64 or PA-RISC - the machines can socket either), their market place was government and other 'high reliability' placements.

So portability is a big concern when considering real-world acceptance in a production environment.

And then there is the ever-growing world of embedded operating systems - from your 'phone to your kitchen blender.
Mostly ARM now (which usually includes a vector processor), but who can say what processor will grab the attention of new equipment designers next.

Yup - I don't feel I have wasted the last three days, nor will I be wasting the next however many days it take to finish this little project.

**Comment by technion** [comment]
I appreciate greatly that you've taken a path previous autoconf attempts refused to - created the ./configure file, without which, I had a very hard time meeting the exact dependencies required to ever use this "more portable" branch.

A point I keep raising however is:
    So portability is a big concern 

Is there any platform you are aware of that the current setup doesn't build on?

    Mostly ARM now

I test regularly with the current build on an RPi with an ARM processor.

    And GCC isn't the primary compiler on *BSD.

I managed to build and run the test suite using [CompCert](http://compcert.inria.fr/) without requiring autoconf.

**Comment by janetizzy** [comment]
Thanks for the feedback.
But help me a bit - what is your point concerning my continuing with my project?

**Comment by jedisct1** [comment]
(shameless plug)
@janetizzy if you need Argon2 that builds with the autotools, you may consider [libsodium](https://download.libsodium.org/doc/)

**Comment by janetizzy** [comment]
I don't see Argon2 among their sources.

**Comment by jedisct1** [comment]
This is the [default password hashing function](https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html) - the [code](https://github.com/jedisct1/libsodium/tree/master/src/libsodium/crypto_pwhash/argon2) is identical to this one, except that optimized vs non/optimized implementations are chosen at run-time, not at compile-time.

**Comment by technion** [comment]
what is your point concerning my continuing with my project?

My concern is only with the suggestion that autotools end up merged here, at which point, I will be one of many people who be using it.

**Comment by janetizzy** [comment]
I made no such suggestion.
Only the courtesy notice to the authors that I was re-using their work.
The inclusion of the 'not ready for a pull request' was a comment on its progress, not a request that it be considered for inclusion.

It is up to the authors of this original work to decide if they want to back-port my changes.
You need to write addressing them on your concerns, not addressing me.
Please.

**Comment by aberaud** [comment]
Argon2 is cruelly missing a proper UNIX build system.
There is no "install" make target, one can't properly cross-compile etc. etc.

I suggest to use CMake as it is higher level and will work well in more environments than autotools, which is just (IMHO) a huge pile of nonsense macros.

Even Autotools would still be a great relief.

**Comment by technion** [comment]
@aberaud I'll just asking - what's "proper" about introducing a dependency on CMake? What platform doesn't the current environment build on, if any?

Is there anything behind this beyond a cargo cult of "we need a complex build system"?

I'll leave this with respected advise from PHK:

https://www.varnish-cache.org/docs/2.1/phk/autocrap.html

**Comment by aberaud** [comment]
@technion I understand what you mean. For sure a simple Makefile will do the job in many cases. Indeed, Autotools is crap.

As a user of the library I mostly just want to do "make install" and start using it. Currently there is no "install" target in the Makefile. It could be added but should handle a few corner cases (installation prefix, DESTDIR etc.). CMake/Autotools would have this built in. Many industrial systems will make use of those "standard" features (install prefix etc.) to integrate the library in more complex systems. Using an existing known build system will make users life much easier.

Cross-compilation would be much easier with a build system. I want to use Argon2 on Android but currently the Makefile makes it a pain. I'm just faster rewriting a Makefile. In general CMake would make porting the build process to new platforms/environments much easier.

**Comment by ranisalt** [comment]
I can do the efforts with CMake, it's a build system I've been using daily for the past months.

**Comment by veorq** [comment]
@technion @jedisct1 @sneves  you guys know better than me: keep the current makefile or get a CMake? @ranisalt kindly offers to set up CMake, should we try it?

**Comment by jedisct1** [comment]
I think the current Makefile is fine. It's super simple and easy to tweak if necessary. It's also easier to use for people not familiar with cmake.

This is not a large project with a lot of dependencies and compile-time checks. If fact, there are none.
People can even just copy the files into their project, and it will work right away.  Which is what people tend to do for builds on non-native targets, even if there is a build system.

**Comment by ranisalt** [comment]
> It's super simple and easy to tweak if necessary.

I have to disagree:

- [These 27-line checks](https://github.com/ranisalt/phc-winner-argon2/blob/4b886205e8a32c584fc8498116d31538f0565689/Makefile#L39-L66) are almost entirely performed automatically by CMake. It is much better to [handle the soname](https://github.com/ranisalt/phc-winner-argon2/blob/9f778dce5ba82b0d1ef37caa3382ccc6a5078261/CMakeLists.txt#L50), too, as it's defined as a variable and not a dangling string.
- [This check](https://github.com/ranisalt/phc-winner-argon2/blob/4b886205e8a32c584fc8498116d31538f0565689/Makefile#L91-L95) is handled by CMake with a variable, `BUILD_SHARED_LIBS`, and the build system does not have to [handle static and shared builds](https://github.com/ranisalt/phc-winner-argon2/blob/4b886205e8a32c584fc8498116d31538f0565689/CMakeLists.txt#L46-L47) differently.
- Better yet, if a dependency is not found (currently only threading support) it fails gracefully with a warning, not spitting error messages like compilers tend to do about undefined references.
- I added a more reliable way to test for SSE2 support as a [separate script](https://github.com/ranisalt/phc-winner-argon2/blob/4b886205e8a32c584fc8498116d31538f0565689/cmake/FindSSE2.cmake) (not involving compiling actual source code).
- There's no need to have and maintain a clean target as CMake does the dirty job.
- CMake allows for [multiple build types](https://github.com/ranisalt/phc-winner-argon2/blob/4b886205e8a32c584fc8498116d31538f0565689/CMakeLists.txt#L12-L16), so we can easily range from debug builds to optimized release builds.

Using Makefile along with another build system just does not fit. If a project uses CMake and wishes to include a Makefile project, it will have to redeclare the entire library again. I had to do [that on node-argon2](https://github.com/ranisalt/node-argon2/blob/master/binding.gyp), which uses gyp.

Also, Makefile syntax is more bashy that CMake. CMake syntax resembles more a programming language. I would use CMake for node-argon2, but node guys made anything but node-gyp a pain in the arse to use.

Note that the branch I'm working on/linked here is very WIP yet, but you can analyze the code to check whether it's a good or bad move :)

**Comment by khovratovich** [comment]
I think if it facilitates the adoption of Argon2 in other projects, we should support it.

@jedisct1 @technion If we do adapt CMake, will we have problems in projects that already use Argon2? Apart from simplicity, are we gonna have compatibility problems if we switch to CMake?

**Comment by jedisct1** [comment]
It will facilitate adoption in projects already using CMake. It will add a prerequisite for others. CMake is popular for C++ projects, not so much everywhere else.

But we won't have compatibility problems.

**Comment by technion** [comment]
@khovratovich 
The objective answer is to narrow it down to:

- Do you want to make CMake an installation requirement? It's not there by default on any server. There are currently 0 dependencies (outside of 'make' and a compiler). 

- Existing projects using this library may then be required to utilise CMake - but will probably find it easier to utilise their own existing build system. There shouldn't be a compat issue.

- Is there a commitment to maintaining CMake long term? Have a look at any CMake file in any project - there are ongoing commits fixing things.

- If nothing else, can there be a consensus that "check for support for memset()" is useless cruft?

**Comment by sneves** [comment]
One advantage of CMake is that it makes the Visual Studio stuff redundant, as CMake naturally generates VS projects as well. 

We already have effectively *two* toolchains in the project; CMake would reduce this to one. It is true that CMake is not everywhere by default, so this is not truly a nobrainer, but it could be worth it.

**Comment by aberaud** [comment]
@technion Many servers don't even have a compiler installed.

Argon2 is a dependency of my project. In the docs I can't ask people to manually copy .so files around on their systems. And what to tell to people using it in larger projects ? Everything is automated expect for Argon2, which requires additional custom work because it doesn't have a standard build system.

> Existing projects using this library may then be required to utilise CMake - but will probably find it easier to utilise their own existing build system.

People don't want nor like to rewrite build systems for libraries they use. They want to clone, build, install and use with no hassle.

Keeping things simple here is just pushing the workload toward users.

**Comment by jrmithdobbs** [comment]
Please stick with make. The project is small enough there's little advantage to cmake since the work has already been done. Forcing users of the lib to have cmake as a build req seems like a barrier to adoption for convenience around and an issue that's already resolved in the current makefile.

**Comment by khovratovich** [comment]
Can we maintain both cmake and the original makefile?

**Comment by atraczyk** [comment]
Having CMake as an installation requirement is a small price to pay for cross-platform building.
The CMake language is sensible and east to use. Even the default Visual Studio project generation creates acceptable project files. For the windows crowd, who would otherwise have to setup a cross-compile environment, CMake is the only sensible solution.

Maintaining CMake and the original makefile shouldn't be too hard and would render the project accessible to a broader range of devs/users.

**Comment by kaldoran** [comment]
Well didn't saw that this isue was speaking about CMake for argon2, but that seems to be a great idea.
Since you already have some "cross platforme" handmade file, that could be a good idea to use CMake which going to avoid maintaining 2 different maker for this project.

For @khovratovich, and in agreement with @atraczyk maintaining both should be that hard to do. Since both are pretty easy to do ( particularly true for CMake, since there is a lot of help all other the internet )

**Comment by ranisalt** [comment]
CMake won't require much maintenance effort, hardly ever it's behavior changes for the most common stuff plus most of the work is automatically done and doesn't need to be explicitly set. Makefile will require the most effort, and it's not much either.

**Comment by Leont** [comment]
I think there are two orthogonal discussion here

1. Our build process is missing features. In particular I've seen mentioned:
    * It's missing an install target, and 
    * There are cross compilation issues
    * Some platforms aren't supported (e.g. HP-UX, AIX)
2. What do we use to implement it? Currently that is GNU make (and Visual Studio, but I'll ignore that for the moment), which is capable enough of implementing these features. Discussing personal preferences is about as productive as discussing favorite programming languages 

Quite frankly I think the first point is the more important bit, and things that need tickets of their own (there may be more such issues). Not being able to fix it in the current framework may be a good reason to switch to something else, but otherwise switching seems of rather neutral value.

**Comment by Leont** [comment]
> As a user of the library I mostly just want to do "make install" and start using it. Currently there is no "install" target in the Makefile. It could be added but should handle a few corner cases (installation prefix, DESTDIR etc.).

I fixed that in #164 .

> Cross-compilation would be much easier with a build system. I want to use Argon2 on Android but currently the Makefile makes it a pain. I'm just faster rewriting a Makefile.

Can you file a ticket for that? And preferably a description of how your own Makefile solved it?

**Comment by aberaud** [comment]
Thanks for adding an install target.
For instance [we need to ranlib the static library](https://jenkins.ring.cx/job/daemon-window-mingw/349/console) when cross-compiling for windows/MinGW. This kind of things is handled automated by CMake/Autotools. Also flags like -ldl are not available/needed on every platform or build type and would be added automatically as needed by CMake/autotools.

**Comment by jrmithdobbs** [comment]
Running ranlib (or an equiv using libtool) is a single extra target. Not a reason to switch to cmake/autotools. Please do not introduce dependencies on either.

**Comment by jrmithdobbs** [comment]
I think a lack of justification for this request merits closing this issue and opening new issues for any specific build system feature requests that are not of the "change the whole build system" form.

**Comment by Leont** [comment]
> We need to ranlib the static library when cross-compiling for windows/MinGW. 

This would be a trivial modification to the Makefile.

> This kind of things is automated by CMake/Autotools. Also flags like -ldl are not needed/available on every platform or build type and would be added automatically as needed by CMake/autotools.

The portability section can definitely be improved, in particular simplified (I don't think Linux and the BSDs really need to be different, and the Win32 environments can clearly be deduplicated), but the actually complicated thing in the Makefile is dealing with the appropriate optimizations. Dealing with that, in particular in a way that doesn't depend on a gcc-like compiler would have far more additional value (e.g. I think a naive CMake port would produce non-working VS project files). I'm not so sure that will be less work in CMake (let alone Autotools).

**Comment by aberaud** [comment]
Having just a raw Makefile is a completely respectable decision. Indeed, most of those things, individually, are trivial to fix. It happens that some tools are already designed to handle most of them properly in many various build environments, with _de-facto_ standard input arguments. However, as a user of the library, I'm happy with anything that works.

**Comment by khovratovich** [comment]
Put on hold
