### ISSUE TITLE
Readme.md file is wrong

### ISSUE THREAD

**Issue by j75** [P-H-C/phc-winner-argon2#138]
It seems that the options have changed: **-h** does not mean *help* anymore but *Sets hash output length to N bytes* (and it requires a parameter value) which was previously **-l** option (it has disappeared now); the usage example should be also modified accordingly.

In order to have the help, the program should be called without any parameter.

**Comment by technion** [comment]
Are you sure you have a fresh build after downloading the latest full source? -h was only recently changed to mean "help", and it does correctly for me:

```
$ ./argon2 -h
Usage:  ./argon2 [-h] salt [-d] [-t iterations] [-m memory] [-p parallelism] [-l hash length] [-e|-r]
        Password is read from stdin
Parameters:
        salt            The salt to use, at least 8 characters
        -d              Use Argon2d instead of Argon2i (which is the default)
        -t N            Sets the number of iterations to N (default = 3)
        -m N            Sets the memory usage of 2^N KiB (default 12)
        -p N            Sets parallelism to N threads (default 1)
        -l N            Sets hash output length to N bytes (default 32)
        -e              Output only encoded hash
        -r              Output only the raw bytes of the hash
        -h              Print ./argon2 usage
```

**Comment by technion** [comment]
@j75 can you confirm if there is anything outstanding here?

**Comment by lucab** [comment]
@j75 I think you are looking at master README while using an old binary version. The change has been in the other direction, see https://github.com/P-H-C/phc-winner-argon2/pull/136.

**Comment by khovratovich** [comment]
Closed.
