### ISSUE TITLE
Raspberry Pi build error

### ISSUE THREAD

**Issue by tommitytom** [P-H-C/phc-winner-argon2#141]
When I 'make' on the Pi (latest Raspbian, fully up to date) I get the following error:
`*** Error in 'cc': double free or corruption (top): 0x016e3ca8 ***`

However even after this appearing, the build still continues and succeeds.  The error also appears multiple times during 'make test'

> $ make test
*** Error in 'cc': double free or corruption (top): 0x01edeca8 ***
cc -std=c89 -pthread -O3 -Wall -g -Iinclude -Isrc  -Wextra -Wno-type-limits src/argon2.c src/core.c src/blake2/blake2b.c src/thread.c src/encoding.c src/ref.c src/test.c -o testcase
Default build
*** Error in 'cc': double free or corruption (top): 0x00c02ca8 ***
argon2i v=16: OK
argon2d v=16: OK
argon2i v=19: OK
argon2d v=19: OK
Force OPTTEST=1
*** Error in 'cc': double free or corruption (top): 0x01230ca8 ***
argon2i v=16: OK
argon2d v=16: OK
argon2i v=19: OK
argon2d v=19: OK

Although it compiles fine when doing it manually, the reason I'm raising this issue is because it is causing issues when compiling with node-gyp (it appears to catch the error and cancels the build).

**Comment by technion** [comment]
Build d7266c4 currently runs fine for me under an older Raspbian:

```
cat /etc/debian_version
7.10
uname -a
Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
gcc -v
gcc version 4.6.3 (Debian 4.6.3-14+rpi1)
```
Currently looking for an option to replicate this.

**Comment by technion** [comment]
Can you humour me and paste the output from

    make genkat

?

**Comment by tommitytom** [comment]
I'm away until Monday, I'll post it up when I return.

**Comment by tommitytom** [comment]
Sorry for the delay!  Here is some info:

`$ cat /etc/debian_version
8.0
$ uname -a
Linux idiot-pi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
$ gcc -v
gcc version 4.9.2 (Raspbian 4.9.2-10)`

Also:
`$ make genkat
*** Error in `cc': double free or corruption (top): 0x01f51ca8 ***
cc -std=c89 -pthread -O3 -Wall -g -Iinclude -Isrc src/argon2.c src/core.c src/blake2/blake2b.c src/thread.c src/encoding.c src/ref.c src/genkat.c -o genkat -DGENKAT
`

**Comment by sneves** [comment]
This is a GCC bug, work around it by not using `-march=native`: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132

**Comment by tommitytom** [comment]
Aha!  Thanks for clearing that up @sneves !
