### ISSUE TITLE
Recommended number of iterations for Argon2i

### ISSUE THREAD

**Issue by yonas** [P-H-C/phc-winner-argon2#144]
I've recompiled my operating system ("LionBSD" based on FreeBSD) to use Argon2i as the default password hashing algorithm in crypt/libcrypt.

I'm wondering what the recommended number of iterations would be?

As an example, OpenBSD uses [8 iterations of bcrypt by default](http://man.openbsd.org/OpenBSD-current/man5/login.conf.5).

**Comment by technion** [comment]
The ideal recommendation is to benchmark your hardware/environment. Any default should change over time as computational power increases. The appropriate benchmarks are discussed in page 17 of the spec sheet:

https://github.com/P-H-C/phc-winner-argon2/blob/master/argon2-specs.pdf

I appreciate that in some cases you just need to pick some default values to ship with. I've been suggesting t = 2, m = 16, and p=1 (this is only a personal view).

**Comment by yonas** [comment]
Thanks, I'll go with those. At some point I'll try to run an automated benchmark to determine the values during install.
