### ISSUE TITLE
Hash Encoding Error

### ISSUE THREAD

**Issue by BenBE** [P-H-C/phc-winner-argon2#152]
When using a 18 bytes salt and 96 byte output, encoding fails:

    $ echo -n "12345678" | ./argon2 123456789123456789 -d -t 16 -m 20 -p 8 -l 96
    Type:		Argon2d
    Iterations:	16 
    Memory:		1048576 KiB
    Parallelism:	8 
    Error: Encoding failed

Doing basically the same, but using 17 bytes for the salt or only 95 bytes for the hash, the hash is encoded properly:

    $ time echo -n "12345678" | ./argon2 12345678912345678 -d -t 16 -m 20 -p 8 -l 96
    Type:		Argon2d
    Iterations:	16 
    Memory:		1048576 KiB
    Parallelism:	8 
    Hash:		158287640a1f8ca408ad8f93dd2a77698437058d106242183a91c1efba56fcacfdc4ce1fddcd429196bc0de10beec4cf32eb82f8f5e2145b7359bd25d774594706adf1b90b48bc67361a91b82ee90d955d6c5a55b10db0012841b34fd4874052
    Encoded:	$argon2d$v=19$m=1048576,t=16,p=8$MTIzNDU2Nzg5MTIzNDU2Nzg$FYKHZAofjKQIrY+T3Sp3aYQ3BY0QYkIYOpHB77pW/Kz9xM4f3c1CkZa8DeEL7sTPMuuC+PXiFFtzWb0l13RZRwat8bkLSLxnNhqRuC7pDZVdbFpVsQ2wAShBs0/Uh0BS
    28.882 seconds
    Verification ok

AND

    $ time echo -n "12345678" | ./argon2 123456789123456789 -d -t 16 -m 20 -p 8 -l 95
    Type:		Argon2d
    Iterations:	16 
    Memory:		1048576 KiB
    Parallelism:	8 
    Hash:		298810cf6ad4feee94925e99e45880a31a135cc1c6f9f76d85c8a7d2f6fedcc10b69401c52e9c31a18665c4b67b142ef77c660be9f645bc343879b6e567e5a7c6d2bf3313b5d9d1fe68ffeb64578b062c21db30f3ad4bf6208042a79aea519
    Encoded:	$argon2d$v=19$m=1048576,t=16,p=8$MTIzNDU2Nzg5MTIzNDU2Nzg5$KYgQz2rU/u6Ukl6Z5FiAoxoTXMHG+fdthcin0vb+3MELaUAcUunDGhhmXEtnsULvd8Zgvp9kW8NDh5tuVn5afG0r8zE7XZ0f5o/+tkV4sGLCHbMPOtS/YggEKnmupRk
    29.184 seconds
    Verification ok

Inspecting the source suggests the problem likely to reside in argon2_encodedlen.

**Comment by SparkDustJoe** [comment]
If you don't mind me asking, why such a long output length?

**Comment by sneves** [comment]
It looks like `to_base64` expects a string long enough to add a `\0` at the end, but `b64len` does not take this extra byte into account. This only seems to happen when the remaining size was exactly right, with no slack bytes. Changing https://github.com/P-H-C/phc-winner-argon2/blob/61428681fead5bbd700030a8afcd0f146536ad88/src/encoding.c#L415 to 
```
 return (((size_t)len + 2) / 3) * 4 + 1;
```
should fix this. If everything checks out, I'll commit this later.

**Comment by daniel-dinu** [comment]
@sneves is right. The encoding fails when `saltlen` and `hashlen` are both multiples of 3. In this case, there is no byte allocated for the string terminator. In all other cases, there is at least one extra byte  which can be used for the string terminator. 
The issue can be fixed more elegantly in `argon2_encodedlen`. `size_t b64len(uint32_t len)` can be optimized to avoid allocation of bytes which are never used. I will push the changes.

**Comment by sneves** [comment]
OK.

**Comment by BenBE** [comment]
> If you don't mind me asking, why such a long output length?
Basically just playing around.

**Comment by sneves** [comment]
I assume this can be closed now?

**Comment by khovratovich** [comment]
Fixed in 	9dc74e1. Thanks to all.
