### ISSUE TITLE
Crediting

### ISSUE THREAD

**Issue by wrathematics** [P-H-C/phc-winner-argon2#160]
Hi,

I've added bindings for your argon2 implementation in an [R package](https://github.com/wrathematics/getPass).  I include the source in the package itself, and point to a copy of the CC0 license in the package's DESCRIPTION file explaining that it governs the relevant files.  I think this more than satisfies the license requirements, but I could list the argon2 authors as "ctb" (contributor) or "cph" (copyright holder) in the package DESCRIPTION file as well.  If you don't want to be listed, that's fine.  If you do, do you have a preference (individual names, "the argon2 team", something else?)

Thanks!

**Comment by veorq** [comment]
Thanks for considering Argon2 in getPass! This usage fulfills the CC0 requirements. No need to explicitly cite us, please just mention the use of Argon2, you may to include the URL https://github.com/P-H-C/phc-winner-argon2.

**Comment by wrathematics** [comment]
Great, thanks! To make it more obvious I'm not asserting authorship of the underlying implementation, I've moved it to its own [set of bindings](https://github.com/wrathematics/argon2).

Thanks for all your great work!
