### ISSUE TITLE
argon2_encodedlen returns too much

### ISSUE THREAD

**Issue by Leont** [P-H-C/phc-winner-argon2#162]
The return value of `argon2_encodedlen` appears to be returning `2` more than the `stren()`, this does not feel like it is intended. While I can imagine `1` more to be intentional (for the null byte), two seems wrong.

Are we sure the logic for it is correct?

**Comment by daniel-dinu** [comment]
``argon2_encodedlen`` was recently modified in 9dc74e1b084ebdbf635a49846f78f5e40848c080 to fix #152. The returned values is equal to ``strlen + 1``.

I noticed that here (https://github.com/P-H-C/phc-winner-argon2/blob/master/src/run.c#L115-L116) ``+ 1`` can be removed.

Is this what you were referring to?

**Comment by Leont** [comment]
> argon2_encodedlen was recently modified in 9dc74e1 to fix #152. The returned values is equal to strlen + 1.

I had missed that completely! Thanks for the fix and sorry for the noise.
