### ISSUE TITLE
Output differs from README

### ISSUE THREAD

**Issue by technion** [P-H-C/phc-winner-argon2#17]
Hi,

Documentation contains this line:

$ ./argon2 password somesalt -t 2 -m 16 -p 4
Type:           Argon2i
Iterations:     2
Memory:         65536 KiB
Parallelism:    4
$argon2i$m=65536,t=2,p=4$c29tZXNhbHQAAAAAAAAAAA$QWLzI4TY9HkL2ZTLc8g6SinwdhZewYrzz9zxCo0bkGY
0.274 seconds

However, I'm seeing this:
$ ./argon2 password somesalt -t 2 -m 16 -p 4
Type:           Argon2i
Iterations:     2
Memory:         65536 KiB
Parallelism:    4
Hash:           4162f32384d8f4790bd994cb73c83a4a29f076165ec18af3cfdcf10a8d1b9066
0.269 seconds

Can you confirm the expected output?

More importantly, can you confirm if "out" from hash_argon2i is supposed to be an encoded string, or if developers still need to manage this?

Edit: I note the existence of the commented encode_string function, however, its prototype suggests it can only be accessed if a user calls the low level API. But a user of the high level API would stand more to gain from an automatically encoded string.

**Comment by veorq** [comment]
Fixed in 91061b23e1cd6b2768ca42277b752cf6a3273e48, thanks!
