### ISSUE TITLE
Fast Verify Argon2 Hash

### ISSUE THREAD

**Issue by CryptoDJ** [P-H-C/phc-winner-argon2#171]
How do you use the fast-verify for PoW described in this white paper? [Egalitarian computing, Alex Biryukov and Dmitry Khovratovich, University of Luxembourg](https://www.usenix.org/system/files/conference/usenixsecurity16/sec16_paper_biryukov.pdf)

I don't see any code or function in this Argon2 repo that implements a fast hash verification.

**Comment by sneves** [comment]
There is not fast hash verification here; Argon2 is as expensive to compute as it is to verify. What you are thinking of is [Equihash](https://www.internetsociety.org/sites/default/files/blogs-media/equihash-asymmetric-proof-of-work-based-generalized-birthday-problem.pdf).

**Comment by khovratovich** [comment]
The Merkle-tree-based PoW based on Argon2 (called MTP) has not been implemented yet.

**Comment by GregoryBetz** [comment]
MTP will be implemented soon ;)

**Comment by khovratovich** [comment]
We are open to any MTP implementation.

**Comment by reubenyap** [comment]
The Zcoin project is working on a MTP implementation. https://github.com/zcoinofficial/mtp

**Comment by khovratovich** [comment]
Cool.
