### ISSUE TITLE
Can we get a release of Argon2?

### ISSUE THREAD

**Issue by josephlr** [P-H-C/phc-winner-argon2#172]
We are looking to start a project using Argon2 as a Debian dependency. To do this, we would need a new release of Argon2, so that Debian can pull it into their packages [here](https://packages.debian.org/stretch/argon2). 

What would need to be done to cut a release of Argon2? I'd be happy to help out in any way I can.

**Comment by khovratovich** [comment]
The issues must be resolved, but I have very little time now for that....

Feel free to suggest PRs that solve the issues.

**Comment by josephlr** [comment]
@khovratovich, I've submitted pull requests that fixed issues #143 #151 #167 (can close these). Issues #133 #171 and #178 are feature requests. Issue #157 looks like a specification misunderstanding, so I think it can be closed as well.

**Comment by veorq** [comment]
Indeed, thanks @josephlr for the PRs. I closed those issues.

We'll create a release.

**Comment by veorq** [comment]
https://github.com/P-H-C/phc-winner-argon2/releases/tag/20161029
