### ISSUE TITLE
Add details of Elixir implementation to the README

### ISSUE THREAD

**Issue by riverrun** [P-H-C/phc-winner-argon2#178]
There is now an Elixir implementation of Argon2. The link to it is [here](https://github.com/riverrun/argon2_elixir).

Is it possible to add this to the list of languages that have bindings for Argon2?

If you need any more details, please let me know.

**Comment by Leont** [comment]
That should be a matter of forking the repo, adding the link and issuing a pull request, really ;-)

**Comment by riverrun** [comment]
Ok
