### ISSUE TITLE
Run time failure for dynamically linked executable with default installation

### ISSUE THREAD

**Issue by josephlr** [P-H-C/phc-winner-argon2#184]
## Steps to reproduce (on 64-bit Ubuntu Linux):

0. Have a clean system with no argon2 libraries installed
1. Clone Repository and run `sudo make install`.
2. Create a test file like this `test.c` example, which calls into argon2:
```c
// test.c
#include <stdio.h>
#include <argon2.h>

int main() {
  printf("%s\n", argon2_type2string(Argon2_id, 1));
  return 0;
}
```
3. Dynamically link in libargon2 by compiling the test against the argon2 shared library with `gcc -Wall test.c -largon2 -pthread -o test`.
4. While the compilation succeeds, running `./test` results in a run time failure: `./test: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory'.

The installer installs the shared object as `libargon2.so`, but it ends up being linked as `libaron2.so`. This can be seen by running `ldd test`:
```
joerichey@joerichey-ubiquity:~/tests/argon2-tests$ ldd test
	linux-vdso.so.1 =>  (0x00007ffe89120000)
	libargon2.so.0 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcd48e43000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcd49208000)
```

### Things not broken
We compiling the test as a _static_ executable, there are no problems.
```
joerichey@joerichey-ubiquity:~/tests/argon2-tests$ gcc -Wall -static test.c -largon2 -pthread -o test
joerichey@joerichey-ubiquity:~/tests/argon2-tests$ ./test
Argon2id
joerichey@joerichey-ubiquity:~/tests/argon2-tests$ ldd test
	not a dynamic executable
```
The linker/executable can find the static library `libargon2.a` but cannot find `libargon2.so`.

## Causes
This issues is caused by a bad `soname` of `libargon2.so.0` passed during the compilation of the shared library. [Here is the location in the Makefile](https://github.com/P-H-C/phc-winner-argon2/blob/master/Makefile#L54).

This `soname` argument means that while the linker will find the `/usr/lib/libargon2.so` file, it will dynamically link the executable to `/usr/lib/libaron2.so.0`, which then causes a failure at run time.

## Fixes
There are two ways to fix this problem. I have tested both methods on my system and they both resolve the issue.

### Fix 1 - Don't care about shared library versioning
For this fix, we just change the `soname` to be `libargon2.so` (or just remove that argument) and always install the shared library to `$PREFIX/lib/libargon2.so`. This means that a system can only have a single version of libargon2 on it at a time. This fix is simpler, but if libargon2 introduces ABI breaking changes and the dynamic library on a system is updated, old executables will break and will need to be relinked.

### Fix 2 - Deal with shared library versioning
For this fix, we keep track of our ABI version number (lets assume that number is 1). Then we install the shared object file to `$PREFIX/lib/libargon2.so.1` and have the `soname` also be `libargon2.so.1`. At installation time, we also symlink `$PREFIX/lib/libargon2.so` to `$PREFIX/lib/libargon2.so.1` (this symlink might not even be necessary). Then, when updating we can install the new version next to the old version and just update the symlink. 

This change is more complex, and we would now have to keep track of ABI breaking changes and bump the version number. If we went with this route, we would probably want to do something similar for the other platforms that support such a thing (like Darwin's `.dylib`). It is also important to note that the approach of the second fix is _significantly_ more common than that of the first.

**Comment by josephlr** [comment]
It should also be noted that this also breaks the install instruction for some language bindings, including [the one for Go](https://github.com/tvdburgt/go-argon2) by [@tvdburgt](https://github.com/tvdburgt).

**Comment by khovratovich** [comment]
Thank you for finding a bug! Let's see if some others comment on the fix.
