### ISSUE TITLE
Useless thread creation for 1-thread version of argon2

### ISSUE THREAD

**Issue by luc-lynx** [P-H-C/phc-winner-argon2#187]
According to the code at
https://github.com/P-H-C/phc-winner-argon2/blob/master/src/core.c#L310

if we need a 1-thread version of argon2 then that 1 thread is created by pthread library and then the main thread will wait for that one. It seems to be an overhead because for 1-thread version of argon2 we can call `fill_segment` function without creating separate thread for that. This improvement will make 1-thread version faster :)

**Comment by khovratovich** [comment]
@sneves Could you comment?

**Comment by sneves** [comment]
It's certainly wasteful to create a thread for the `p=1` case. The performance difference of not doing so won't be noticeable for typical cases, but it might affect the throughput if e.g. you're a server computing many `p=1` hashes simultaneously, in effect having 2x the number of threads as needed.

**Comment by josephlr** [comment]
One thing to consider might be the scenario where you want to use argon2 but in a situation that dosn't have threading support. This sort of change could be extended to allow for argon2 to be compiled or used without threads (only allow p=1 of course).

**Comment by luc-lynx** [comment]
@josephlr sounds sane. Actually, in this case we can allow p != 1 case by carrying out all computations sequentially (of cause it'll be slower) and add optional OpenMP support for that loop (the corresponding `#pragma` declarations will be ignored if there is no OpenMP support in the target system).

**Comment by technion** [comment]
@josephlr Whilst I agree, that would take more than fixing an unneeded code path, and wouldn't get fixed unless someone spent time carefully inserting #ifdefs in the code. Not that I'm against it.

**Comment by sneves** [comment]
It turns out to be a simple thing, I submitted a PR for it just now.

**Comment by sneves** [comment]
I suppose this can be closed now.
