### ISSUE TITLE
Do not pass the password as a command-line argument

### ISSUE THREAD

**Issue by dbakker** [P-H-C/phc-winner-argon2#19]
If the `argon2` command line utility is ever used for anything but testing purposes, this is a bad idea:

    ./argon2 pwd salt [-d] [-t iterations] [-m memory] [-p parallelism]

The problem is that other users of the same system can see which programs are running and what their command line arguments are (for example using `top -c`).

It would be better to read the password from stdin like this:

    echo "pwd"|./argon2 salt [-d] [-t iterations] [-m memory] [-p parallelism]

**Comment by veorq** [comment]
Fixed in 45590c26421fc0e9444768d1fc48f1eb26ced979
