### ISSUE TITLE
List of open source projects that use Argon2

### ISSUE THREAD

**Issue by luc-lynx** [P-H-C/phc-winner-argon2#190]
In my opinion it would be great to have in the README a list of opensource projects that use Argon2. For example, [Django uses](https://github.com/django/django/blob/master/django/contrib/auth/hashers.py#L298) Argon2i for password hashing (512kb, t=2, p=2).

**Comment by khovratovich** [comment]
It is just hard to track, but generally I am open to it.

**Comment by luc-lynx** [comment]
Actually you don't need to manually track it, I suggest just adding a corresponding section into README and accepting PR's :)

**Comment by YogSottot** [comment]
You can add [opendht](https://github.com/savoirfairelinux/opendht/tree/master/src/argon2)

**Comment by technion** [comment]
The difficulty with "accepting PRs" is that it assumes they are consistently provided, which isn't always a safe assumption once a project gets past its first few months of fame.

**Comment by leafcutterant** [comment]
KeePass joins the ranks: [](http://keepass.info/news/n170109_2.35.html)

**Comment by leafcutterant** [comment]
KeePass joins the ranks:  [http://keepass.info/news/n170109_2.35.html](http://keepass.info/news/n170109_2.35.html)

**Comment by luc-lynx** [comment]
And [default parameters](https://fossies.org/windows/misc/KeePass-2.35-Source.zip/KeePassLib/Cryptography/KeyDerivation/Argon2Kdf.cs) are ```tcost = 2, mcost = 1Mb, threads=2```

**Comment by SCDeveloper** [comment]
Dynamic (https://dynamic.duality.solutions) uses Argon2d for its Mining Algo.

// main configurable Argon2 hash parameters
context.m_cost = 250; // Memory in KiB (~256KB)
context.lanes = 4;    // Degree of Parallelism
context.threads = 2;  // Threads
context.t_cost = 1;   // Iterations

**Comment by WOnder93** [comment]
> context.lanes = 4; // Degree of Parallelism
> context.threads = 2; // Threads

Why do they set lanes to 4, but threads to only 2?

**Comment by SCDeveloper** [comment]
https://github.com/duality-solutions/Dynamic/commit/ad30c81374c39cfb10a72bf9df1d4d5ae74c2388

I actually upped it to 4 in a commit a day ago.

**Comment by SCDeveloper** [comment]
What we need is fast verify for Argon2d though.

**Comment by khovratovich** [comment]
On hold due to inactivity

**Comment by spencerlievens** [comment]
Has any movement or development by other parties happened in-terms of Argon2d fast verification?
