### ISSUE TITLE
Argon2 lib interferes with Blake2 lib

### ISSUE THREAD

**Issue by Wasnix** [P-H-C/phc-winner-argon2#197]
Argon2 lib exports blake2b* symbols which are also part of Blake2. 

The linker should use a version-script to exclude symbols from Blake2: _... -Wl,--version-script=version map_

Minimal contents of file version.map:
`
{
    global: *;

    local:
blake2*;
};
`

**Comment by sneves** [comment]
Under which platform is this happening? [Linux](https://github.com/P-H-C/phc-winner-argon2/blob/master/Makefile#L63) specifically uses `fvisibility=hidden` and `A2_VISCTL` to avoid this situation.

**Comment by khovratovich** [comment]
Closed until further details
