### ISSUE TITLE
phc-string-format repo out of date & confusing

### ISSUE THREAD

**Issue by hynek** [P-H-C/phc-winner-argon2#199]
Hi,

I’ve already ran into two instances of where https://github.com/P-H-C/phc-string-format is confusing people.  In this case passlib – Python’s main password hashing library – [changed their defaults](https://bitbucket.org/ecollins/passlib/issues/88) because the spec claims that the “The default [hash] output length is 32 bytes (43 characters).”

It’s also [out of date](https://github.com/P-H-C/phc-string-format/issues/1) and doesn’t reflect the current standard at all.

Could we retire the repo?  And then add something up to date here?   ATM it seems to do more harm than good.

**Comment by sneves** [comment]
I completely agree.

**Comment by Asmod4n** [comment]
As a binding author i would like to see `decode_string` and `encode_string` to be in their own library or be publicly exposed in argon2.
At the moment i have to ship argon2 with my binding and cannot link to system installed versions.

**Comment by Leont** [comment]
> As a binding author i would like to see decode_string and encode_string to be in their own library or be publicly exposed in argon2.

Yeah that sounds sensible to me.
