### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ofek** [P-H-C/phc-winner-argon2#203]
Can we get a new release soon? I'd like to use some of the recent fixes.

**Comment by khovratovich** [comment]
Fine with me

**Comment by zorun** [comment]
Could we get a new release? The current one is almost one year old, and I have seen a report of an "invalid opcode" crash that is apparently resolved in the git version.

**Comment by zorun** [comment]
Disregard the "invalid opcode" thing, it's the same issue as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828779

But it would still be nice to have a newer release :)

**Comment by ofek** [comment]
@veorq @khovratovich Any plans for this soon?

**Comment by khovratovich** [comment]
I want to do it immediately after closing #205 and #201

**Comment by solardiz** [comment]
I think #204 also must be fixed, at least by replacing the word "seconds" with "seconds of CPU time".

**Comment by daniel-dinu** [comment]
A new release is available here: https://github.com/P-H-C/phc-winner-argon2/releases/tag/20171227
