### ISSUE TITLE
Missing header file on VS2015

### ISSUE THREAD

**Issue by ranisalt** [P-H-C/phc-winner-argon2#205]
It's been reported on ranisalt/node-argon2#78 that there's no `inttypes.h` on VS2015. There's a polyfill project [here](https://code.google.com/archive/p/msinttypes/) but it probably misses the architecture-driven optimizations, yet seems to suffice and is used in libgit2 and ffmpeg.

That's a rather [large change](https://github.com/ranisalt/phc-winner-argon2/commit/4564ccdb3a073b263e086c672b4279ebffc7ec02) but might work.

**Comment by sneves** [comment]
Strange; Visual Studio 2015 certainly has `inttypes.h`.  [Even 2013](https://msdn.microsoft.com/en-us/library/dn495455(v=vs.120).aspx) does as well. Additionally, there have been no complaints from the automated [Windows builds](https://ci.appveyor.com/project/P-H-C/phc-winner-argon2).

**Comment by Leont** [comment]
Just a guess: `inttypes.`h may available only in C++ mode. Microsoft has a habit of ignoring C99 and later, but it generally quite up-to-date with C++, so sometimes you need to enable C++-mode to get modern C-features. I wouldn't be surprised if this was one of those features.

**Comment by khovratovich** [comment]
Any updates on that?
