### ISSUE TITLE
Fine-grained memory setting

### ISSUE THREAD

**Issue by goblin** [P-H-C/phc-winner-argon2#211]
The argon2 CLI utility only allows setting memory via _n_, to 2^n KiB. However, if I'm reading it right, the paper says that the algorithm can use any multiple of 4p KiB of memory, where _p_ is parallelism:

> • Memory size m can be any integer number of kilobytes from 8p to 2^32 − 1. The actual number of blocks is m', which is m rounded down to the nearest multiple of 4p.

I'd like to use 11GiB of memory, why doesn't the CLI let me?

Thanks

**Comment by sneves** [comment]
I'm not a fan of changing the meaning of `-m` at this point, but I suppose an argument of a fine grained amount of memory could be added.
