### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sonOfRa** [P-H-C/phc-winner-argon2#237]
Hi,

it's been over a year since the last release tag was set, and quite a few things, especially wrt the build process have been fixed in that time. I maintain the argon2 package in Gentoo Linux and have to carry a few of the patches made since 20161029 in my package to build it properly. Is there any chance of a new release (possibly including #236) soon, so that I can drop the patches and transition to that version? This would be especially practical in the course of maybe getting argon2 stabilised on Gentoo whenever the version of cryptsetup with argon2 support gets stabilised as well.

**Comment by daniel-dinu** [comment]
A new release is available here: https://github.com/P-H-C/phc-winner-argon2/releases/tag/20171227
