### ISSUE TITLE
Seeking technical analysis of a proposed Ethashv2 for ASIC resistance

### ISSUE THREAD

**Issue by jamesray1** [P-H-C/phc-winner-argon2#249]
Please see: https://github.com/ethereum/EIPs/pull/969. With the recently announced Bitmain E3 miner, a pull request has been created to modify the FNV constant in the Ethash algorithm to have 5 FNV constants instead. Ethereum is seeking commentary on how likely this change is to brick the Bitmain E3 miner, as well as any other ASICs that may be secretly running, as well as how resistant it would be to future ASICs (probably not very) e.g. with programmable logic.

**Comment by AirSquirrels** [comment]
I will clarify we have no intention for this change to prevent future ASIC development. The explicit goal is the break the existing ASIC with a minimal possible change with considerations for making mask fixes or edits (using larger hamming weights for the new constants).

**Comment by technion** [comment]
Can you clarify where there is actually an issue with this codebase at all?

If there's a bug here I want to fix it, but aside from looking for people to get involved in another set of blockchain projects I'm not seeing what the question is.

**Comment by jamesray1** [comment]
There was no question specifically on your codebase.
