### ISSUE TITLE
Argon2 command line utility (run.c): Add possibility to encode Salt 

### ISSUE THREAD

**Issue by charno** [P-H-C/phc-winner-argon2#263]
Since currently the salt is directly interpreted by the command line utility it's not possible to use specific salts which contain for example 0-bytes, and other characters can be hard to transfer depending on the used shell.

A possible solution would be to introduce an additional command line parameter (-b). If this parameter is set, the salt is interpreted as base64.

**Comment by khovratovich** [comment]
The command line version does not have to have full functionality, so it is fine that some salts are not taken.

**Comment by charno** [comment]
Sorry to disagree, but we use the command line version to check hashes (which are provided from a DB). Since in the DB there are hashes present with null-bytes, we need this change. Is there a special reason you don't want to include the pull request?
