### ISSUE TITLE
New Implementation in Python

### ISSUE THREAD

**Issue by jwsi** [P-H-C/phc-winner-argon2#288]
Hi there,

I've just created a new Python implementation (using cffi) which supports keyed hashing and other lower-level options. The implementation is designed for developers who want the level of control that your C implemenation provides, but in Python.

I would be grateful if you could add this to your README under the "Bindings" section.

My implementation is located [here](https://github.com/ultrahorizon/pyargon2)

Thanks.

**Comment by khovratovich** [comment]
Hi, thanks, please submit a PR
