### ISSUE TITLE
Will argon2 detect instruction sets automatically?

### ISSUE THREAD

**Issue by guojize** [P-H-C/phc-winner-argon2#291]
For example, if I build `argon2` on a CPU with AVX instruction set enabled, can I use the same binary on a CPU without AVX?
Or I need to disable these instruction sets to make the executable portable?

**Comment by sneves** [comment]
There is presently no such mechanism; CPU dispatch decisions are all made at compile time.

**Comment by guojize** [comment]
So what do I need to do when compiling if I want to make the executable portable?

**Comment by jedisct1** [comment]
Use libsodium?

**Comment by josephlr** [comment]
The executable should be portable by default. You will only build with AVX512 (or whatever) if you explicitly tell your compiler to build with those features. This is true even if the host (building the program) supports the extensions
