### ISSUE TITLE
Issue regarding Variable Hash Output less then  or equal to 64 bytes/Characters

### ISSUE THREAD

**Issue by ithompson1959** [P-H-C/phc-winner-argon2#293]
I have been writing my own version of the Argon2 function, I have been unable to verify the finalise stage of the output hash.
I can produce the correct state array all the way before the final Variable length Hash function. But can't get the required return hash to match the reference output. Upon further investigation. I have found in the reference release that the Blake2b_update function appears to over write the the beginning of the input buffer when the output length required is less than 65 bytes the over written data is the last 4 bytes of input buffer. This renders your tag results different from mine.

I have checked the documentation for both Argon2 and Blake2b. Blake2b document indicates their should be no issue processing an input of 1028 bytes ie, the length little endian encoded + 1024 Bytes Message (Final XOR of last blocks in state array). Neither does your documentation make any indication that the variable length hash function should over write the beginning of the input buffer if it is longer than 1024 Bytes. (which is what it appears to do.)

The error appears to be in the blake2b_update function called via the blake2_long Function.
    if (outlen <= BLAKE2B_OUTBYTES) {
        TRY(blake2b_init(&blake_state, outlen));
        TRY(blake2b_update(&blake_state, outlen_bytes, sizeof(outlen_bytes)));
        TRY(blake2b_update(&blake_state, in, inlen));
        TRY(blake2b_final(&blake_state, out, outlen));  << Set break point here

the blake_state buffer shows the last 4 bytes of the input buffer and not the outlen as stated by the specification.

Is the function rigth in which case the specification needs more details specifying?
Or is the blake2B_update function wrong?

Also I would recommend  a couple of more test vectors at least one with Memory at 2560 and lanes 4 this should test slices with more than 128 blocks in them.

Keep up the good work!

**Comment by sneves** [comment]
> the blake_state buffer shows the last 4 bytes of the input buffer and not the outlen as stated by the specification.

This is as would be expected; internally, BLAKE2b keeps a 128-byte input buffer, and every 128 bytes it will compress the full buffer into a new chaining value. So after 1028 bytes, it is entirely expected that the input buffer only contains the last 1028 % 128 = 4 bytes of `in`.

It would, perhaps, be more useful if you would describe what you're doing.

**Comment by ithompson1959** [comment]
Thanks for the reply, I was rolling my own version of the Argon2 function. Your comments lead me to check something in my Blake2 function which has now resolved the issue. Despite my Blake2 function passing the test vectors stated in RFC 7693 it was at fault. So just goes to show a good set of test vectors check against is important!

My implementation is using C#, There were no errors in my Argon2 code just the Blake2 function when processing multi blocks.

Just for completeness the following snippet is what generates my Variable Length Hash

        // Variable Length Hash Function for Argon 2
        internal static byte[] VLHash(byte[] Message, int MDLen)
        {
            byte[] VLHash = new byte[MDLen];
            Array.Resize(ref Message, Message.Length + 4);
            Array.Copy(Message, 0, Message, 4, Message.Length - 4);
            Array.Copy(GenerateLE32((UInt32)MDLen), 0, Message, 0, 4);
            if (MDLen > 64)
            {
                UInt32 Parts = (UInt32)((MDLen >> 5) - 2);
                for (UInt32 Ptr = 0; Ptr < Parts; Ptr++)
                {
                    Message = BLAKE2("Blake2b", Message, new byte[0], 64);
                    Array.Copy(Message, 0, VLHash, Ptr << 5, 32);
                }
                Message = BLAKE2("Blake2b", Message, new byte[0], (int)(MDLen - (Parts << 5)));
                Array.Copy(Message, 0, VLHash, VLHash.Length - Message.Length, Message.Length);
            }
            else
            {
                VLHash = BLAKE2("Blake2b", Message, new byte[0], MDLen);
            }
            Array.Resize(ref VLHash, MDLen);
            return VLHash;
        }

My understanding of your blake2_long was wrong I realise now that you process blocks if they are complete in the buffer and process the whats left over in the blake2_final function. Where as my Blake2 processes the whole message in a single call.

Apologies for my mis-understanding.
