### ISSUE TITLE
trap invalid opcode 

### ISSUE THREAD

**Issue by nicraMarcin** [P-H-C/phc-winner-argon2#308]
Hi, I have strange problem.
I use argon2 in my app. Everything works on my laptop where I'm making my app. It also works if I copy my binary file to ovh vps server, works on my VirtualBox (debian 10) but I doesn't work on production :( When I try to login (verify password) I got `Bad instruction` and program crashes.
In kernel.log I got:
```
Nov  3 15:38:48 dev kernel: [  945.069440] traps: nmsapi[2152] trap invalid opcode ip:558ac8d6c342 sp:7f89ad596dc0 error:0 in nmsapi[558ac885d000+742000]
Nov  3 15:38:53 dev kernel: [  950.699662] traps: nmsapi[2162] trap invalid opcode ip:5579b088a342 sp:7f69a8bd2dc0 error:0 in nmsapi[5579b037b000+742000]
Nov  3 15:39:12 dev kernel: [  969.694740] traps: nmsapi[2183] trap invalid opcode ip:5583ab3e3342 sp:7fbf227dedc0 error:0 in nmsapi[5583aaed4000+742000]
Nov  3 15:40:15 dev kernel: [ 1032.369646] traps: nmsapi[2275] trap invalid opcode ip:5626c74d7342 sp:7f48f4ef4dc0 error:0 in nmsapi[5626c6fc8000+742000]
Nov  3 15:42:20 dev kernel: [ 1157.786570] traps: nmsapi[7151] trap invalid opcode ip:565397e7e342 sp:7f87c8b68dc0 error:0 in nmsapi[56539796f000+742000]
```

this is the instruction which causes crash:
```cpp 
oatpp::String argon2string = "$argon2id$v=19$m=65536,t=2,p=2$ODM5RmM2WFo$MO6lzmXATL+medYB/QPujMRxngZ0Qu2B5/pwxNLOaIM";
    int validityCode = argon2id_verify(argon2string->c_str(), plainPassword->c_str(), plainPassword->getSize());
```
My system

>    Static hostname: dev
>          Icon name: computer-vm
>            Chassis: vm
>         Machine ID: 6fcc73612d0744aaadf79214b8b410b2
>            Boot ID: e9b7c6b8f954467dbf109198fb7037ca
>     Virtualization: kvm
>   Operating System: Debian GNU/Linux 10 (buster)
>             Kernel: Linux 4.19.0-12-amd64
>       Architecture: x86-64
> 
and this is pure system installed from netinstall. 

What can cause my problem?

**Comment by sneves** [comment]
> Everything works on my laptop where I'm making my app. It also works if I copy my binary file to ovh vps server, works on my VirtualBox (debian 10) but I doesn't work on production

I suspect this is the problem---you're copying a binary compiled to a specific instruction set (say, AVX2) and running it on a different machine that may not have it.

The `Makefile` defaults to having `OPTTARGET ?= native`, which uses whatever instructions are available on the host machine. Try using, say, `OPTTARGET ?= core2` or something that is guaranteed to exist everywhere and see if it improves anything.

**Comment by nicraMarcin** [comment]
@sneves Thank you for answer.
Do you cuggest to add to my CMakeLists.txt `add_compile_options(-march=core2)`?

**Comment by sneves** [comment]
The safe choice would be to have no specific `-march=...` setting at all. Did the CMake configuration file have one before?

**Comment by nicraMarcin** [comment]
No, CMakeLists didn't include march option

**Comment by sneves** [comment]
OK, the machine where it fails has almost none of the common instructions found in recent x86_64 chips. 

Are you using `opt.c` or `ref.c` when building the Argon2 code? How are you compiling Argon2, exactly?

**Comment by nicraMarcin** [comment]
I compiled with `core2`, `x86-64` but the same problem :(
```
Thread 4 "nmsapi" received signal SIGILL, Illegal instruction
```
