### ISSUE TITLE
Invalid Hash generated on Raspberry Pi 4 with latest 64 bit Linux deb 11

### ISSUE THREAD

**Issue by guil-g** [P-H-C/phc-winner-argon2#329]
Hash generated does not match with argon2.online. Pls. help.

**Comment by ufukty** [comment]
I think if you share parameters you used for argon2.online and Linux, it would make it easier to people for helping you

**Comment by guil-g** [comment]
$ echo '123456789012345678901234567890' | argon2 salzwasser
Type:           Argon2i
Iterations:     3
Memory:         4096 KiB
Parallelism:    1
Hash:           2e38a5c031c9c5d2c55b11f2ef35724e8f9bca28a111f834196374ee210d398c
Encoded:        $argon2i$v=19$m=4096,t=3,p=1$c2Fsendhc3Nlcg$LjilwDHJxdLFWxHy7zVyTo+byiihEfg0GWN07iENOYw

$ uname -a
Linux ras 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux

$ apt list argon2
Listing... Done
argon2/stable,now 0~20171227-0.2 arm64 [installed]
argon2/stable 0~20171227-0.2 armhf

Compiling from sources makes no difference.

**Comment by ufukty** [comment]
`echo` command appends a newline character at the end of string. Try with `echo -n` to disable that behaviour.

**Comment by ufukty** [comment]
Bash:

```sh
$ echo -n "123456789012345678901234567890" | argon2 "salzwasser" -i -t 3 -m 12 -p 1
```

Website:

```
Parallelism factor:1
Memory cost: 4096
Iterations: 3
Hash length: 32
```

Output is same:

```
$argon2i$v=19$m=4096,t=3,p=1$c2Fsendhc3Nlcg$VFoCUnJ9BRisFg0SLR2tBPoijHBvkNYL9WGlwPWstS0
```

**Comment by guil-g** [comment]
Thank you very much.  This solved the issue.
