### ISSUE TITLE
Confusing Constants, core.h, Word vs QWord

### ISSUE THREAD

**Issue by SparkDustJoe** [P-H-C/phc-winner-argon2#41]
Excerpted from core.h, line 34
`/* Memory block size in bytes */`
`ARGON2_BLOCK_SIZE = 1024,`
`ARGON2_WORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 8,`
`ARGON2_QWORDS_IN_BLOCK = 64,`

According to the definitions here:
http://edwin-wang.com/2012/02/bit-nybble-byte-word-dword-qword/
and here:
https://msdn.microsoft.com/en-us/library/2s70e2x4.aspx

If we have 1024 bytes per block (8192 bits), and a QWORD is 8 bytes (64 bits), then by definition we should have 128 QWORDS, not 64.

**Comment by sneves** [comment]
You're right. Sticking to this terminology ` ARGON2_WORDS_IN_BLOCK` should be ` ARGON2_QWORDS_IN_BLOCK`, and `ARGON2_QWORDS_IN_BLOCK` should be `ARGON2_OWORDS_IN_BLOCK`. The latter refers to the number of 128-bit words within a block.

Alternatively, one could get rid of the 'word' nomenclature and use something clearer, but nothing comes to mind at the moment.

**Comment by SparkDustJoe** [comment]
There is already an 'ARGON2_ADDRESSES_IN_BLOCK'.  I'm still digging into the spec, so how these values play against each other in the code is still a bit unclear.  I'm attempting a port to C# to compare performance and as a way to learn how Argon2 works in depth.

**Comment by khovratovich** [comment]
The Argon2 WORD is intended to be 64-bit as it is atomic in the underlying Blake2b. The QWORD should perhaps be DWORD.

Both are nothing to do with addresses-in-block, as the latter refers to the number of block indices fitting into a block

**Comment by veorq** [comment]
@khovratovich  Any action on that? if not, please close

**Comment by khovratovich** [comment]
I am on travel, will resolve tomorrow. Do not see a problem of keeping it
as is though.

On Thu, Dec 3, 2015 at 1:15 AM, JP Aumasson <notifications@github.com>
wrote:

> @khovratovich <https://github.com/khovratovich> Any action on that? if
> not, please close
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/P-H-C/phc-winner-argon2/issues/41#issuecomment-161274327>
> .
>



-- 
Best regards,
Dmitry Khovratovich

**Comment by SparkDustJoe** [comment]
If there is justification to keep it as is to be consistent with other parts of the code, I would suggest to at least make the justifications part of the documentation, so that auditors or implementors of other languages based on the source are clued in.

**Comment by veorq** [comment]
Yeah I'd prefer to stick to the historical terminology of word/double/quad being 16/32/64 bits.

**Comment by khovratovich** [comment]
Please feel free to change  `ARGON2_WORDS_IN_BLOCK` to `ARGON2_QWORDS_IN_BLOCK`, and `ARGON2_QWORDS_IN_BLOCK` to `ARGON2_OWORDS_IN_BLOCK`
