### ISSUE TITLE
Small values for memory cost allow to create hashes that can’t be verified

### ISSUE THREAD

**Issue by hynek** [P-H-C/phc-winner-argon2#42]
While playing with the parameters (mainly to get fast hashes for unit tests), I’ve run into a problem where argon2 will happily create a hash but fail to verify it:

```
$ echo -n "password" | ./argon2 somesalt -t 1 -m 3 -p 2
Type:		Argon2i
Iterations:	1
Memory:		8 KiB
Parallelism:	2
Hash:		b53b9d234b12abfe90ad7866cb8f494dd1b07d48022f17fa8c6029c68a1805a1
Encoded:	$argon2i$m=8,t=1,p=2$c29tZXNhbHQAAAAAAAAAAA$tTudI0sSq/6QrXhmy49JTdGwfUgCLxf6jGApxooYBaE
0.001 seconds
Error: Decoding failed
```

Setting parallelism down to 1 fixes it FWIW.

I’m not smart enough to deduce from your paper why that is, but maybe it should be documented and/or the hash shouldn’t be created in the first place.

**Comment by veorq** [comment]
Fixed in fc2198590886152bc695c836f370eb4487793938, thanks!
