### ISSUE TITLE
spec vs reference implementation

### ISSUE THREAD

**Issue by kerukuro** [P-H-C/phc-winner-argon2#46]
1. In section 3.2 Operation, the spec defines that the first two blocks should be set like this:
B[i][0] = H'(H0||i||0), B[i][1] = H'(H0||i||1).
However, the reference implementation initializes them like this:
B[i][0] = H'(H0||0||i), B[i][1] = H'(H0||1||i).

2. I can't match the description of H' function (in the same section) to the implementation. The description of H' function states that r=tao/32-1, and V[r+1] is absent if 64 divides tao. However, that can't be true because this would give us 992-byte hash when we request 1024-byte output (Tag = A1||A2||...||Ar, with V[r+1] absent, where r = 1024/32 - 1 = 31, and each A is 32 bytes). Also, when tao is less than 32, the definition results in a negative value of r.

**Comment by khovratovich** [comment]
The spec is wrong, I will fix that.

**Comment by veorq** [comment]
Please update `argon2-specs.pdf` when you're done :)

**Comment by khovratovich** [comment]
Fixed in 3938228
