### ISSUE TITLE
Javascript implementation

### ISSUE THREAD

**Issue by ranisalt** [P-H-C/phc-winner-argon2#47]
I've created bindings for Javascript based on this implementation: https://github.com/ranisalt/node-argon2
Currently I didn't implement an option to choose between Argon2i and Argon2d but that's on the way.

**Comment by technion** [comment]
Surely the reference library isn't going to include a binding for every single language? I'm saying this as someone who wrote a Ruby gem and doesn't expect to see it here.

**Comment by veorq** [comment]
Python bindings are part of the codebase so far, but yeah we don't want to include all bindings. The best is probably to leave them all out and provide a link in the README, and/or how to get them using the language's packaging systems.

**Comment by technion** [comment]
@veorq Would definitely support leaving them all out. Both myself and @ranisalt have elected to directly reference the source repository, which is a good way of guaranteeing there's been no tampering - would recommend all future bindings do the same. It does however, mean the first step of using for Node or Ruby is to download Python code.

@ranisalt Is your binding pushed to npm? Perhaps a PR documenting various language packages into the README is the way to go here.

**Comment by ranisalt** [comment]
> @ranisalt Is your binding pushed to npm? Perhaps a PR documenting various language packages into the README is the way to go here.

Yes, that was my point. I do prefer to have a listing of bindings to different languages rather than being merged to this repository. The package [is here](https://www.npmjs.com/package/argon2).

**Comment by technion** [comment]
Suggested text...

Bindings
------------
Bindings for popular languages are provided and supported by third parties. For more information, see these links:

Python: https://pypi.python.org/pypi/argon2
JavaScript: https://www.npmjs.com/package/argon2
Ruby: https://github.com/technion/ruby-argon2

**Comment by veorq** [comment]
Done :-)
https://github.com/P-H-C/phc-winner-argon2#bindings
