### ISSUE TITLE
Expose `argon2_core` or add `argon2_verify_i`

### ISSUE THREAD

**Issue by bwesterb** [P-H-C/phc-winner-argon2#49]
`argon2_core` would be handy to officially have in the argon2 API.  (That is: move from `core.h` to `argon2.h`.)

Alternatively, please add the missing `verify_i`.

**Comment by veorq** [comment]
Thanks, `verify_i` added in fd5684ee8ef9aa9c2673896dc9362320bb3ef5a9. 

Do you see cases where `argon2_hash` would be insufficient and `argon2_core` needed?

**Comment by hynek** [comment]
I personally would like to have an API that allows me to pass a context and the type without further indirections.  That would mirror nicely `argon2_hash()`/`argon2_verify()`.

***

Bas mentioned on the ticket referenced above that he’d like to set `threads` independently from `lanes`.

**Comment by bwesterb** [comment]
When we want to compute a hash with 32 lanes on a dual-core processor, it is faster to just spawn two threads instead of 32.  Thus, I would like access to the `threads` field.  If, however, `libargon2` would be smart enough to spawn at most the number of cores of the CPU (by default), then that would do as well.

**Comment by veorq** [comment]
Makes sense, added `argon2_core` to `argon2.h` in cee4402b10ddf3abca7e65c8b0c990f8f85fdd3e.

**Comment by bwesterb** [comment]
Thank you!
