### ISSUE TITLE
Use at most as many threads as the computer has cores?

### ISSUE THREAD

**Issue by bwesterb** [P-H-C/phc-winner-argon2#53]
At the moment `argon2i_hash` (and friends) will use as many threads as the lanes/parallelism parameter.  If however we compute a 32-lanes argon2-hash on a 2-core machine, it does not make a lot of sense to spawn 32 threads.  One can work around this by using `argon2_core` and setting the `threads` field of the executed `argon2_context` to the number of cores on the machine.

Would you think it's ok if `argon2i_hash` and friends cap `threads` to the number of cores on the machine?  If so, I can write a patch.

**Comment by khovratovich** [comment]
No, it is not needed. We could give a warning.

**Comment by veorq** [comment]
Let's leave it as it is then
