### ISSUE TITLE
switch from CC0 license to something more common?

### ISSUE THREAD

**Issue by stapelberg** [P-H-C/phc-winner-argon2#54]
Currently, the repository is licensed under CC0. As per https://github.com/blog/1964-open-source-license-usage-on-github-com (specifically https://cloud.githubusercontent.com/assets/282759/6517300/9dc14536-c367-11e4-9a63-b23a3d75af78.png), this is a very unusual license to use for code.

You can also search through the Debian archive and see that not many packages have code (!) (as opposed to artwork, documentation, etc.) that’s licensed under CC0: https://codesearch.debian.net/perpackage-results/file%3Adebian%2Fcopyright%20CC0/2/page_0

I know of at least one big company where the internal guidelines require special approval for making use of CC0. One of the issues apparently seems to be section 2 of the CC0 license, where contributors waive all rights.

I think it’d be good to license the code under a more common license, so that it can be more easily adopted by distributions, enterprises and individuals alike.

What do you think?

Thank you for considering.

**Comment by khovratovich** [comment]
I do not have strong preference here, and would live with the MIT licence as well.

**Comment by veorq** [comment]
CC0 is equivalent to "public domain", which makes it easiest to be used by third-party projects. It puts no obligation whatsoever on users, and creates no liability or risk for the authors. In my experience this kind of license is what companies and proprietary software like the best. Lawyers will just want to make sure that the code includes copyright notices.

**Comment by stapelberg** [comment]
@veorq I don’t want to start an endless license debate, and I’m not a lawyer myself. That said, my original post was based on a lawyer’s statement. CC0 certainly is not equivalent to public domain. If you want to license your code as public domain, can I suggest that you explicitly do that instead of licensing it as CC0 and saying that’s equivalent?

**Comment by veorq** [comment]
@stapelberg: Lawyers disagree on the validity of claims like "I release this in public domain". Public domain isn't a license. Releasing under CC0 solves the problem, for it grants to users the exact same right as "public domain". I've seen cases where lawyers refused to use code claimed "released in public domain", but never for code under public domain-like licenses: CC0, WTFPL, or Unlicense.

**Comment by stapelberg** [comment]
Our experiences are very different then. WTFPL is another example of something that my employer will never ever use, I imagine Unlicense will be the same situation.

@veorq Given that @khovratovich would be fine with MIT (and I think MIT is undisputably accepted in every organisation that uses open source software), is there any specific reason why MIT isn’t an option for you?

**Comment by veorq** [comment]
Interesting experience, curious to know the reasons. Is it in any specific
context or some specific product? Is the concern related to patents? (CC0's
contains no patent license unlike some other software licences—but not MIT
iirc)

MIT requires to add the license and copyright notice in any distribution of
the software, and I don't see why we would want to impose this on users.

**Comment by stapelberg** [comment]
> Interesting experience, curious to know the reasons. Is it in any specific
> context or some specific product?

If you’re asking about WTFPL, there is no specific context/product, it’s just that the license is not considered sound legally. AIUI, “do what the fuck you want” is too vague for the lawyers.

> Is the concern related to patents? (CC0's contains no patent license unlike some other software licences—but not MIT iirc)

No, the concern is not related to patents. If you want to cover patents, Apache2 is the most common license that most organizations agree with, AFAIK.

**Comment by technion** [comment]
Several included components are listed as separately CC0 licensed, so note you couldn't necessarily simply change the LICENSE file here and call it done.

The FSF's legal team don't appear consistent with the issues raised in this thread: https://www.gnu.org/licenses/license-list.html
