### ISSUE TITLE
Digest sizes < 12 fail to verify

### ISSUE THREAD

**Issue by hynek** [P-H-C/phc-winner-argon2#55]
Hi,

a user of argon2_cffi found an edge case where argon2 will create a hash but verification will fail with a decoding error:  hynek/argon2_cffi#4

I could narrow it down to digest lengths that are less than 12 bytes (I used your run.c for that, not my bindings).

**Comment by veorq** [comment]
Thanks, we'll investigate

**Comment by hynek** [comment]
Pleas note that he found more such cases.  Feel free to ask questions on the linked ticket. :)

If you'd be interested we could build a test harness in Python for Argon2 or something.

**Comment by DRMacIver** [comment]
I can answer questions here too. :-)

The two other cases that fail in the same way - that is, a hash is created successfully but the resulting hash cannot validate the original password, are when the hash length or salt length are > 512. 

These three cases are the only failures I'm aware of, though it's possible that they're hiding other issues that the test in question may uncover if these are fixed.

**Comment by technion** [comment]
Is this caused by #77  ?

**Comment by technion** [comment]
In terms of progressing this.. does Argon2 actually make sense to support the salt lengths that it does? I'm having visions of someone writing a frontend with salts that are 0xFFFFFFFF in length, and calling it "maximum possible Argon2 strength".

Would setting ARGON2_MAX_SALT_LENGTH to 512 be appropriate?

I appreciate this thread appears to suggest there's a bigger issue behind it - but it would resolve part of this issue.

**Comment by khovratovich** [comment]
Found the bug, working on the patch

On Thu, Jan 21, 2016 at 4:53 AM, technion <notifications@github.com> wrote:

> In terms of progressing this.. does Argon2 actually make sense to support
> the salt lengths that it does? I'm having visions of someone writing a
> frontend with salts that are 0xFFFFFFFF in length, and calling it "maximum
> possible Argon2 strength".
>
> Would setting ARGON2_MAX_SALT_LENGTH to 512 be appropriate?
>
> I appreciate this thread appears to suggest there's a bigger issue behind
> it - but it would resolve part of this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/P-H-C/phc-winner-argon2/issues/55#issuecomment-173443814>
> .
>



-- 
Best regards,
Dmitry Khovratovich

**Comment by khovratovich** [comment]
Currently the verification procedure rejects all the strings where salts and outputs are too short or too long. The exact restrictions are specified in the description of argon2i_verify() in argon2.h. 

For more permissive processing you can change the respective constants (ARGON2_MAX/MIN_DECODED_SALT/AD/OUT_LEN) or call decode_string() explicitly as argon2_verify() does.

We may consider increasing these constants if it is really needed.

**Comment by hynek** [comment]
Hm the description of argon2i_verify() in argon2.h says:

```c
/**
 * Verifies a password against an encoded string
 * Encoded string is restricted as in validate_inputs()
 * @param encoded String encoding parameters, salt, hash
 * @param pwd Pointer to password
 * @pre   Returns ARGON2_OK if successful
 */
```

and there is no `validate_inputs()` definition which makes one to read the source in `core.c`.

That’s a bit too much scavenger hunt to my taste to determine the valid value ranges for a function.
