### ISSUE TITLE
Document recommended parameter settings

### ISSUE THREAD

**Issue by ocharles** [P-H-C/phc-winner-argon2#59]
What are some good starting points for the time, memory and parallelism parameters?

**Comment by khovratovich** [comment]
The detailed procedure is given in the spec, Section 9.

Alternatively, set 128 MB (m=128000), t=1, p=4 and play with the parameters under your constraints.

**Comment by ocharles** [comment]
Thanks, I think that's worth mentioning in the README, but I will make a pull request for that.
