### ISSUE TITLE
Insecure defaults

### ISSUE THREAD

**Issue by floyd-fuh** [P-H-C/phc-winner-argon2#6]
I (and most practical security people) very much dislike the idea of insecure defaults. A developer who doesn't know what a salt is, is going to use zero byte salts all the way. If you provide this as a default, developers will use it. If you say zero bytes are default, a developer thinks "well, if argon2 says that's default it can't be bad, right?". If you don't believe me, here's a blog post about something similar that we often enough in the wild: http://www.modzero.ch/modlog/archives/2011/11/04/the_apple_idioten_vektor_iv/index.html

Now you still have the chance to change this interface. Later on you might have all this backward-compatibility stuff to handle.

I propose two options: 

1. Random salt generation and showing it to the user. I see that this might lead to the question of secure random entropy source for different plattforms etc., so might not be the best option
2. Make -s a mandatory option and exit with non zero exit code

Same for password. Can you imagine what happens if a developer blindly compares two outputs of argon2 to check if a password is correct and forgets to specify the -p parameter for both invocations? Every password will work (as argon2 will use "password" for every run).

**Comment by veorq** [comment]
You're 100% right. We'll fix.

**Comment by veorq** [comment]
Command-line tool now *requires* a password and a salt.

Bench and KATs generation have been moved to separate binaries.
