### ISSUE TITLE
Stable libargon2.so interface?

### ISSUE THREAD

**Issue by lucab** [P-H-C/phc-winner-argon2#61]
I'm in the process of packaging libargon2 for Debian, and it looks like libargon2.so doesn't declare any soname.

I'm currently [adding a local soname](http://anonscm.debian.org/cgit/collab-maint/argon2.git/tree/debian/patches/makefile.patch?h=debian/sid#n21) to the library, but for compatibility reasons it would be better if proper soname versioning is introduced directly here (upstream).

Do you consider the libargon2 library API/ABI stable enough to start adding a soname and tracking compatibility, so that it can be safely installed and provided system-wide?

**Comment by veorq** [comment]
Thanks for packaging this, libargon2.so.0 sounds good as a soname, added in 9c141611ec3b3294bfcad86ebc928f9cdf19cba5

I don't expect the API/ABI to change now, at least not frequently. Let's as for @khovratovich's approval to.

**Comment by lucab** [comment]
On a side note, libargon2 has no symbol control, so currently all the symbols are exported (even the internal details). [This](https://gist.github.com/lucab/3fc63cc1669f3f5dc783) is the current list of all symbols available in the .so at the moment.

I see several issues with it:
 * internal symbols are part of the ABI
 * blake2_* symbols re-exported (I assume this is an unexpected side-effect, not a wanted feature)
 * some methods not namespaced under `argon2*` (`verify_d`, `verify_i` and `error_message` are very generic names)

This can be better handled by reworking the include file and using the visibility controller (at least on gcc and clang).

@khovratovich what do you think about it? Can I go on detailing the issues and submitting PRs? Changes could be a bit intrusive on the API, but better fixing this earlier IMHO.

**Comment by tml** [comment]
:+1: For cleaning up the ABI, although I'm not adverse to seeing the blake2 symbols exported here; perhaps I'm overlooking the potential downside.

**Comment by lucab** [comment]
Lacking further feedback, I proceeded and detailed the issues I saw. Those are:
 * #74 - `argon2_error_codes` can be made private
 * #75 - Generic methods naming
 * #76 - Internal symbols exported in shared library

I'd suggest to address these before tagging a new release, as they'll introduce some breaking changes which you may want to sneak in before applying the '.0' soname. I have branches (that still need polishing) for most of those, but again I'd like some feedback before submitting those.

@tml: I added my answer to your point in #76.

**Comment by veorq** [comment]
@lucab: apologies for the lack of feedback

Ping @khovratovich @daniel-dinu

**Comment by khovratovich** [comment]
I have no opinion on #76. What is recommended?

**Comment by khovratovich** [comment]
Apologies for not getting earlier on that.

**Comment by technion** [comment]
@tml in terms of potential downside, I can speak from the scrypt experience - as soon as someone linked against that library, and OpenSSL, you would break the compile because of the SHA256 name collisions.

I'd imagine it wouldn't be hard to see someone using this Argon2 library alongside a library that includes blake2, having the same issues.

**Comment by tml** [comment]
I was sold by @lucab's initial response, but I appreciate all the discussion. :+1:

**Comment by lucab** [comment]
On the same topic, to be addressed for stabilization/compatibility concerns before next release:
 - [ ] #84 - Functions declared but not defined

**Comment by technion** [comment]
Just pinging @lucab that #84 is closed now.

**Comment by lucab** [comment]
It looks like all issues mentioned here have been fixed now. If everybody is happy about the current status of the public interface (argon2.h), can we please tag a new release and declare the .so stable?

**Comment by technion** [comment]
I'd really like to see #113 land in stable - but otherwise, I'd really like to see a stable tag.

**Comment by veorq** [comment]
Fine for me, and a new release would be good. I'll let @khovratovich or @daniel-dinu approve this.

**Comment by lucab** [comment]
I just saw that there is a pending 1.3 revision for the algorithm, so maybe it makes sense to land that one too first and then tag the release later.

**Comment by technion** [comment]
@lucab  that's not pending - it's merged already. You'll note all the test vectors have changed.

**Comment by lucab** [comment]
This has been closed, yet there are no new stable releases. Did somebody perhaps forget to push the tag?

**Comment by daniel-dinu** [comment]
The new stable release is coming soon. As far as I can see, all other issues from this thread have been addressed.
