### ISSUE TITLE
exit(-1) on thread creation/join failures

### ISSUE THREAD

**Issue by markrwilliams** [P-H-C/phc-winner-argon2#64]
Before anything - thanks for publishing this!

In reading through argon2's source, I noticed three occurences of `exit(-1`) in `core.c`:

https://github.com/P-H-C/phc-winner-argon2/blob/master/src/core.c#L289
https://github.com/P-H-C/phc-winner-argon2/blob/master/src/core.c#L308
https://github.com/P-H-C/phc-winner-argon2/blob/master/src/core.c#L322

...which means programs that link against argon2 might terminate unexpectedly.
Consider, for example, the following Python program that uses [argon2_cffi](https://github.com/hynek/argon2_cffi):

````python
import resource
import sys

from argon2 import PasswordHasher

if sys.argv[1:]:
    resource.setrlimit(resource.RLIMIT_NPROC, (1, 1))


ph = PasswordHasher()
print ph.hash("s3kr3tp4ssw0rd")
print "More code runs."
````

When run on a Linux system with no arguments it runs in its entirety.  However, with additional arguments, the program reduces the allowed number of processes/threads below what argon2 requires, and so argon2 causes an unexpected termination:

````
$ python example.py
$argon2i$m=512,t=2,p=2$DOoJURupbQWaLfR2ye12tQ$kiBvcn+l+6RBRTaUVB7UiQ
More code runs.
$ python example.py 1
ERROR; return code from argon2_thread_create() is 11
````

An API that reserves the right to terminate your program seems troubling, especially as it might enable an attack.  A web server under resource pressure, for example, could be pushed into a cascading failure.

At the very least this behavior should be documented.  I'll be happy to submit a PR either for an API change or for a documentation change.

Thanks again for argon2!

**Comment by veorq** [comment]
Thanks for noticing this, it's bad practice indeed and should be fixed. Feel free to submit a PR :-)
