### ISSUE TITLE
argon2_compare - export

### ISSUE THREAD

**Issue by technion** [P-H-C/phc-winner-argon2#70]
Hi,
I had been using argon2_compare as an exported function, but fcabf6f6 broke this.

The function is properly namespaced and I was wondering if this decision could be reviewed. I don't believe it's inappropriate for an external application to decide to use the low level argon2i(), which would followed by encode_string() (both of which are exported) and then argon2_compare().

**Comment by technion** [comment]
I've had some email correspondence about this issue, with a view the low level API shouldn't be exported at all. So to clarify, reasons you would use the low level API:

- You want to use context->secret
- You want to use context->ad
- You want to hash with other than ARGON2_DEFAULT_FLAGS;

I'm completely in favour of a high level API being as simple as possible, but that doesn't mean power users should lose the ability to access to low level functions.

**Comment by technion** [comment]
Pinging anyone anywhere regarding this?

**Comment by sneves** [comment]
I don't have a problem with exporting this function, FWIW.

**Comment by technion** [comment]
I guess I'll make a PR and see what happens.

**Comment by technion** [comment]
I'm going to close this off in the interests of encouraging the more important goal at this point - calling the API stable.
