### ISSUE TITLE
Implications of http://eprint.iacr.org/2016/027

### ISSUE THREAD

**Issue by alterstep** [P-H-C/phc-winner-argon2#72]
What are the implications of http://eprint.iacr.org/2016/027? Should we wait for Argon3?

**Comment by khovratovich** [comment]
Answered here http://permalink.gmane.org/gmane.comp.security.phc/3606

**Comment by luc-lynx** [comment]
The link in the above comment seems to be broken. Can anyone add the actual answer to the comments?

**Comment by sneves** [comment]
It is mirrored here: http://lists.openwall.net/phc-discussions/2016/01/13/1
