### ISSUE TITLE
enum argon2_error_codes should not be part of the public interface

### ISSUE THREAD

**Issue by lucab** [P-H-C/phc-winner-argon2#74]
`argon2.h` currently exposes a `enum Argon2_ErrorCodes` and the related `argon2_error_codes` typedef. However, this enum is not used by any public library method, as errors are signaled by returning non-zero integers.

In order to improve privacy (stop apps abusing internal error codes), compatibility (guard code changing across versions) and simplifying versioning, I would suggest to move this enum declaration in a private place and to update the doc not to mention `ARGON2_OK`.

**Comment by lucab** [comment]
Additionally, currently all error codes are positive integers while all methods deal with *signed* integers. This could led to confusion and bugs, as seen on #66. Should all methods be more specific and operate on *unsigned int* instead?

**Comment by khovratovich** [comment]
I am usually in favor of unsigned int wherever it is meant, though there is a point of view that uints lead to bugs when comparing to zero in loops/whiles.

**Comment by lucab** [comment]
I'd limit this report to error codes only (the `int` currently returned by public method and the fed into `error_message()`). I can't imagine a scenario where somebody may want to use them as loop conditions. Other int/uint mismatches exist in the library, but I would address them separately (I saw a TODO in place yesterday). 

Instead, after some further research I saw that some bindings (like the ruby one) already re-export them while most of the other bindings don't. So the options on the table are:
 * leave the enum in place and return an enum instead of an int. Users will need to update/re-build every time the enum change. This make dynamic lib quite uncomfortable, but allows bindings to hardcode a list of errors (which needs to be separately maintained/updated). As a packager I personally dislike this, but developers may think otherwise.
 * make the enum private and move to unsigned int. It makes the library more opaque (no way to constant-match error codes in apps), but allow for better forward compatibility. Additionally you can either return `unsigned int` (arch-specific) or uint16_t (fixed width). I'm a supporter of using fixed width types, but I may understand not everybody love them.

**Comment by khovratovich** [comment]
I support the latter option; feel free to propose a patch. @veorq @sneves counteropinions?

**Comment by daniel-dinu** [comment]
I argue for the first option: 

As a developer who uses the library, I would like to have access to the error codes. I want to know why a function call returned an error and to be able to take some actions for some error codes. 

Once the library is stable, the chances of future changes in the enum are very low.

The other int/uint mismatches you identified are linked to the use of the error codes?

**Comment by lucab** [comment]
> The other int/uint mismatches you identified are linked to the use of the error codes?

I casually spotted https://github.com/P-H-C/phc-winner-argon2/blob/master/src/argon2.c#L179 yesterday when checking another PR, this is one is not related to error codes. I didn't specifically look for other ones, though.

**Comment by sneves** [comment]
A third option would be to remain with `int`, but change the error codes to be negative. This would support the common C idiom `if( argon2_f() < 0 ) handle_failure()`, but also to be more picky with the error codes if necessary.

Regarding hiding the error codes, I would ask: what kind of abuse is enabled by having access to particular error codes?

**Comment by SparkDustJoe** [comment]
If the error codes bubble up to the presentation or customer layer they
could expose specific faults usefull for attacks. If they are consumed in
the logs but the customer only gets "Something went wrong." then it's only
a troubleshooting tool.

**Comment by lucab** [comment]
> Regarding hiding the error codes, I would ask: what kind of abuse is enabled by having access to particular error codes?

Every time a new error code is introduced (like in 1456057de8770f13dec60a8a93643250d5c09bc8), the value of `ARGON2_ERROR_CODES_LENGTH` gets redefined. For the users of the library that are case -witching on error code, this means that:
 * if it is a foreign binding, it needs to maintain its own list of error codes in sync, otherwise it could receive "unmapped" error codes
 * dynamically linked programs need to be rebuilt, as their `ARGON2_ERROR_CODES_LENGTH` value is wrong (this is a subtle case, as the ABI is kept compatible but the API changed)

Apps and library are tightly coupled via the API on error codes. Whether good or not, it is a design choice. So far I've seen all the approaches in use:
 * openssl returns opaque errors and expose functions to translate them
 * libusb exposes a public enum (with negative values)
 * libuv just plainly #define (negative) integer constants

As everything, this is a trade-off between compatibility and transparency. Being more opaque means freedom for you for breaking/changes stuff but apps knowing less details. Viceversa transparency means tighter coupling between apps and lib.

I'm happy with whatever you choose, just that the current situation (public enum, all positive values, functions using signed int) is probably not the smarter mix.

**Comment by technion** [comment]
Every one of these errors is a coding bug. I'm saying, if an end user can trigger ARGON2_TIME_TOO_LARGE, you've got more problems than how you report the error.

If however, I happen to make a call with m = 12, instead of 1<<12 (ie, this happened), I'm far more appreciative of having more than an integer to go on in terms of what went wrong.

From the point of view of the Ruby binding, it behaves the way it does it means because one less FFI binding is one more point for simplification. I have no strong opinion on whether this is the best way to do it.

**Comment by lucab** [comment]
So it looks like this is the last (from my side) issue open on API stabilization. I see that not everybody is happy about removing error codes and I also understand they are useful from a developer/user PoV.

As said above, at this point I don't have any specific preference, but I just would like to reach a consensus here about if/how to expose and typify error codes, in order to close #61.

@veorq @sneves @daniel-dinu @khovratovich can you please sum up the details on which way do you want to go for the final stable API?

**Comment by veorq** [comment]
No strong opinion here, but I'd rather simplify the life of users of the lib than that of its developers :)

**Comment by technion** [comment]
Can we get this closed as it was fixed by #108?
