### ISSUE TITLE
Some public methods missing namespacing (too generic naming)

### ISSUE THREAD

**Issue by lucab** [P-H-C/phc-winner-argon2#75]
Most of the library interface sits in the `argon2*` namespace. Some methods however are generically named:
 * `verify_d()`
 * `verify_i()`
 * `error_message()`

Those could conflict with other library or app-specific functions. I suggest to rename them to prepend the `argon2` namespace prefix. The verify functions may perhaps follow the `argon2(d|i)_verify` scheme for compact-ness?

This change will of course break the public interface for existing apps and bindings.

**Comment by daniel-dinu** [comment]
I agree. 
Perhaps argon2_verify_(d|i) is better.

**Comment by lucab** [comment]
You are right, I noticed them only after filing the initial report.

Another option is `argon2(d|i)_ctx_verify` or `argon2(d|i)_verify_ctx` if you want to be consistent with the existing ones above (and could be augmented with a generic `argon2_verify_ctx` with an additional argon2_ type argument).

I've no special preferences, and the patches I currently have need some rebasing anyway.

**Comment by daniel-dinu** [comment]
This is a good idea. 
It might be a good idea to use the  `_ctx` suffix for all low-level API function signatures. This way it is easy to differentiate between low-level and high-level functions.

**Comment by khovratovich** [comment]
Sounds good. If no objections, could you make a patch?


On Fri, Jan 22, 2016 at 11:50 PM, daniel-dinu <notifications@github.com>
wrote:

> This is a good idea.
> It might be a good idea to use the _ctx suffix for all low-level API
> function signatures. This way it is easy to differentiate between low-level
> and high-level functions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/P-H-C/phc-winner-argon2/issues/75#issuecomment-174079139>
> .
>



-- 
Best regards,
Dmitry Khovratovich

**Comment by daniel-dinu** [comment]
Fixed by d9b0bafe37dbb94f22748b7bc73268b073e4934c and 01b2c59c7406b8022226bea1973831deeec57581.
