### ISSUE TITLE
Internal symbols exported in shared library

### ISSUE THREAD

**Issue by lucab** [P-H-C/phc-winner-argon2#76]
libargon2.so is built without any visibility control options. By default, clang/gcc export all non-local symbols. The result is the library currently exposing [all these symbols](https://gist.github.com/lucab/3fc63cc1669f3f5dc783). This means:
 * internal details are part of the ABI
 * some `blake2_*` symbols are available, but not really defined in headers

On posix platforms, I suggest to implement visibility control by explicitely marking exported function [as explained in the doc](https://gcc.gnu.org/wiki/Visibility).

**Comment by lucab** [comment]
@tml voiced for keeping the blake2 symbols. I'm personally against it because:
 * those functions are not declared in argon2.h anyway
 * there is already a dedicated `libb2` for whoever needs it
 * it's a compatibility/maintenance cost (changes there impact the soname as a whole)
 * in argon2 context, they look like internal implementation details, not something needed by the libargon2 users

**Comment by sneves** [comment]
FWIW, I agree: it seems to me like a bad idea to export the blake2 symbols here.

**Comment by daniel-dinu** [comment]
I also think that it is a bad practice to export unnecessary symbols.

**Comment by lucab** [comment]
Ok, will switch visibility default to hidden and only mark stuff under argon2.h to be exported (as sketched in https://github.com/lucab/phc-winner-argon2/commit/2f2c5684ddb7244245c693d589261fdb7fae57cc). This is for Linux only for the moment, as I'm not sure about the other OS; *BSD may want to follow, but for the rest I don't know.
