### ISSUE TITLE
Functions declared but not defined

### ISSUE THREAD

**Issue by daniel-dinu** [P-H-C/phc-winner-argon2#84]
The following functions are declared in `argon2.h`, but they are not defined in `argon2.c`:
`
int argon2di_ctx(argon2_context *context);
int argon2ds_ctx(argon2_context *context);
int argon2id_ctx(argon2_context *context);
`

I see 2 options:
* we remove them from `argon2.h`
* we add implementations for them in `argon2.c` that return an error code `ARGON2_TYPE_NOT_SUPPORTED`

Opinions?

**Comment by jedisct1** [comment]
+1 for removing them.

**Comment by lucab** [comment]
What is the reason why they are there?

If it is an historical artifact (pre-phc?) and you don't care about compability with the past, I guess it's fine to just remove them. Same applies if you don't plan to implement di / ds / id support in the library in the future.

**Comment by technion** [comment]
Given that they cannot possibly work in the current state, I cannot see BC being a thing, and would +1 on just removing them.
