### ISSUE TITLE
Improper initialization of ctx in argon2_verify?

### ISSUE THREAD

**Issue by hynek** [P-H-C/phc-winner-argon2#90]
Hi,

I’ve run into a very weird test failure that sadly only happens in CI: https://travis-ci.org/hynek/argon2_cffi/jobs/104569433 : `Secret pointer is NULL, but secret length is not 0`

(please ignore and forgive the super-confusing naming; hash_secret is simply the generic hashing function in my bindings.  When I decided on the name I didn’t realize that what you call `key` in the paper is called `secret` in the bindings.  And just `hash` is a built-in function in Python which I didn’t want to shadow.)

Squinting at the [code](https://github.com/P-H-C/phc-winner-argon2/blob/master/src/argon2.c#L294-L321), it seems like verify relies on `ctx` being 0-initialized which you usually can’t for regular lokal variables?

The `hash` function on the other hand does it properly and initializes all ctx fields: https://github.com/P-H-C/phc-winner-argon2/blob/master/src/argon2.c#L203-L204

So my guess is I’ve accidentally triggered an incomplete initialization bug?  A `memset(0)` should be enough I guess.

**Comment by technion** [comment]
I'm fairly sure I introduced this in 6eedc8ed18. I had to introduce zeroing in several other places to make that commit work. I can't replicate this bug on my system - but such is the case with no-properly initialized memory.

I do prefer the memset option - but this codebase already zeroes everything explicitly so I've kept the existing style. Making a PR now.
