### ISSUE TITLE
What to do about bad salting?

### ISSUE THREAD

**Issue by cgmb** [P-H-C/phc-winner-argon2#96]
I think there were some issues with salting in the node bindings (ranisalt/node-argon2#11). What are the consequences of using a low-entropy salt, and do you guys have any suggestions on fixing things after the fact?

**Comment by SparkDustJoe** [comment]
When in doubt, prehash the salt, or allow the user to not specify one,
generate it internally using an RNG and the Argon process itself with low
values or the RNG and several rounds of Blake to ensure an attacker can't
gain much ground by manipulation of the OS RNG.  But that means allowing
some mechanism for the user to retrieve that generated salt for user
specific parameters.

**Comment by sneves** [comment]
The only hard requirement for the salt is that it be *unique*. In the spec the salt is actually called *nonce* for this reason. Therefore, low-entropy salts are not a problem, so long as they don't repeat.

**Comment by cgmb** [comment]
Most don't repeat. Out of 4096 hashes I generated, 4016 had unique salts. These were the 80 duplicates:

```
19 77+977+977+977+977+97w
17 AAAAAAAAAAAAAAAAAAAAAA
 6 77+9AAAAAAAAAAAAAAAAAA
 4 77+9Uu+/ve+/ve+/ve+/vQ
 2 cgAAAAAAAAAAAAAAAAAAAA
 2 77+9e++/ve+/ve+/ve+/vQ
 2 77+977+9QxDvv73vv73vvw
 2 77+977+9Oe+/ve+/ve+/vQ
 2 77+977+9Je+/ve+/ve+/vQ
 2 77+977+9Eu+/ve+/ve+/vQ
 2 77+977+9C++/ve+/ve+/vQ
 2 77+977+9ce+/ve+/ve+/vQ
 2 77+977+9AAAAAAAAAAAAAA
 2 77+977+977+9Ju+/ve+/vQ
 2 77+977+977+9CO+/ve+/vQ
 2 77+977+977+9bO+/ve+/vQ
 2 77+977+977+977+9G++/vQ
 2 77+977+977+977+9cu+/vQ
 2 77+977+977+977+977+9Qg
 2 77+977+977+977+977+9FA
 2 77+977+977+977+977+9Dw
```

(generated with: `cat hashes.txt | cut -d'$' -f4 | uniq -cd | sort -rn`)

**Comment by technion** [comment]
I don't think you want to mess with this too much. A test harness should be able to test a salt of "somesalt" and not have the low level API decide it's not random enough or something silly.

That said, my Ruby bindings generate the salt using SecureRandom, and you only override that by seeing the :salt_do_not_supply parameter. My documentation then states "If you are providing your own salt, you are probably using it wrong". And yet, I am already aware of an implementation that is doing just that, and doing so poorly.

I definitely favour being defensive, but at some point, you have to accept an API can't prevent someone actively trying to abuse it.

**Comment by cgmb** [comment]
@technion, I think you misunderstood a little. These salts were generated using the node-argon2 API the 'correct' way. It's since been fixed, but I presume that there are library users that did everything right, but still ended up with these weak salts in their database.

The bindings are less than 2 months old, so if 1% of salts are either all-`U+0000` or all-`U+FFFD`, maybe it's not something to be too concerned about. It doesn't actually affect me as a user; I just noticed the bug and want to be sure it's properly handled.

If fixing the salt going forward is sufficient, then that's been done and this issue can be closed.
