### ISSUE TITLE
Off-by-one in blake2b_long?

### ISSUE THREAD

**Issue by veorq** [P-H-C/phc-winner-argon2#98]
Reported on freenode/##crypto:

21:38 < doomrobo> in blake2b_long, it appears to be calculating V_{r+1} = H_{tau - 32r}(V_r) instead of V_{r+1} = H_{tau-32r}(V_{r-1}). The relevant code is here
                  https://github.com/P-H-C/phc-winner-argon2/blob/ea8545a3ad16b7be2a49288050debdba7b312b9a/src/blake2/blake2b.c#L363
21:39 < doomrobo> and relevant part of the spec: https://imgur.com/ko7IoXA

(credit to Michael Rosenberg)

**Comment by khovratovich** [comment]
Seems to be the spec bug

**Comment by khovratovich** [comment]
Fixed in 079c5a6
